-- ============================================================================
-- NutriBoost — dữ liệu món Việt
--
-- FILE NÀY ĐƯỢC SINH TỰ ĐỘNG. ĐỪNG SỬA TAY.
-- Nguồn: packages/seed/src/data/ingredients.ts và packages/seed/src/data/dishes.ts
-- Sinh lại: npm run seed -- --emit-sql
--
-- Chỉ số của món được tính từ thành phần bằng recompute_dish_nutrients() ở cuối file,
-- nên sửa một nguyên liệu sẽ tự động cập nhật mọi món dùng nguyên liệu đó.
-- ============================================================================

-- 1. Thực phẩm: nguyên liệu và món
insert into public.foods (slug, name_vi, kind, category, serving_name, serving_grams, kcal_per_100g, protein_g, carb_g, fat_g, fiber_g, sugar_g, sodium_mg, source_ref)
values
  ('gao-te', 'Gạo tẻ', 'ingredient', 'Ngũ cốc', null, null, 344, 7.9, 76.2, 1, 1, 0, 14, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('com-trang', 'Cơm trắng', 'ingredient', 'Ngũ cốc', 'bát', 200, 130, 2.7, 28.2, 0.3, 0.4, 0, 5, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('pho-tuoi', 'Bánh phở tươi', 'ingredient', 'Ngũ cốc', null, null, 143, 3.2, 31.5, 0.2, 0, 0, 12, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('banh-mi', 'Bánh mì', 'ingredient', 'Ngũ cốc', 'ổ', 100, 265, 8.6, 52.6, 1.5, 0, 0, 480, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('mi-an-lien', 'Mì ăn liền', 'ingredient', 'Ngũ cốc', 'gói', 75, 448, 9, 63, 17, 0, 0, 1100, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('khoai-tay', 'Khoai tây', 'ingredient', 'Củ', null, null, 92, 2, 20, 0.1, 1.4, 0, 6, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('khoai-lang', 'Khoai lang', 'ingredient', 'Củ', null, null, 119, 1.1, 27.9, 0.2, 1.3, 0, 11, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('thit-bo-nac', 'Thịt bò nạc', 'ingredient', 'Thịt', null, null, 118, 21, 0, 3.8, 0, 0, 60, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('thit-heo-nac', 'Thịt heo nạc', 'ingredient', 'Thịt', null, null, 139, 19, 0, 6.5, 0, 0, 55, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('thit-ga-ta', 'Thịt gà ta', 'ingredient', 'Thịt', null, null, 199, 20.3, 0, 13.1, 0, 0, 70, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('trung-ga', 'Trứng gà', 'ingredient', 'Trứng', 'quả', 50, 166, 13, 1, 11.6, 0, 0, 130, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('ca-basa', 'Cá basa', 'ingredient', 'Thủy sản', null, null, 87, 16, 0, 2.5, 0, 0, 60, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('ca-thu', 'Cá thu', 'ingredient', 'Thủy sản', null, null, 145, 19, 0, 7.5, 0, 0, 80, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('tom-tuoi', 'Tôm tươi', 'ingredient', 'Thủy sản', null, null, 90, 18, 1, 1.5, 0, 0, 150, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('dau-hu', 'Đậu hũ', 'ingredient', 'Đậu và hạt', null, null, 95, 9, 3, 5.5, 0, 0, 10, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('dau-phong', 'Đậu phộng', 'ingredient', 'Đậu và hạt', null, null, 573, 25.8, 16, 44.5, 5.5, 0, 8, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('sua-tuoi-khong-duong', 'Sữa tươi không đường', 'ingredient', 'Sữa', 'ly', 200, 61, 3.2, 4.8, 3.3, 0, 0, 45, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('sua-chua-khong-duong', 'Sữa chua không đường', 'ingredient', 'Sữa', 'hộp', 100, 61, 4.1, 5.4, 2.6, 0, 0, 45, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('sua-dac', 'Sữa đặc có đường', 'ingredient', 'Sữa', null, null, 321, 8, 54.4, 8.5, 0, 54.4, 110, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('rau-muong', 'Rau muống', 'ingredient', 'Rau', null, null, 25, 2.7, 3, 0.3, 1.8, 0, 40, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('cai-ngot', 'Cải ngọt', 'ingredient', 'Rau', null, null, 17, 1.7, 2.4, 0.2, 1.2, 0, 30, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('ca-chua', 'Cà chua', 'ingredient', 'Quả', null, null, 20, 0.6, 4.2, 0.2, 1, 0, 10, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('dua-leo', 'Dưa leo', 'ingredient', 'Quả', null, null, 16, 0.8, 2.9, 0.1, 0.7, 0, 5, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('ca-rot', 'Cà rốt', 'ingredient', 'Củ', null, null, 39, 1, 8.8, 0.2, 2.5, 4.7, 70, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('hanh-la', 'Hành lá', 'ingredient', 'Gia vị', null, null, 22, 1.3, 4.2, 0.2, 1.4, 0, 15, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('toi', 'Tỏi', 'ingredient', 'Gia vị', null, null, 127, 5.5, 28.1, 0.2, 1.8, 0, 15, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('chuoi-tieu', 'Chuối tiêu', 'ingredient', 'Quả', 'quả', 100, 97, 1.5, 22.4, 0.3, 2.6, 15, 1, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('tao-tay', 'Táo tây', 'ingredient', 'Quả', 'quả', 150, 52, 0.3, 13.8, 0.2, 2.4, 10.4, 1, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('dau-an', 'Dầu ăn', 'ingredient', 'Chất béo', 'thìa', 10, 899, 0, 0, 99.9, 0, 0, 0, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('duong-trang', 'Đường trắng', 'ingredient', 'Gia vị', 'thìa', 5, 400, 0, 99.9, 0, 0, 99.9, 1, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('nuoc-mam', 'Nước mắm', 'ingredient', 'Gia vị', 'thìa', 5, 35, 5, 3.6, 0, 0, 0, 7851, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('muoi-an', 'Muối ăn', 'ingredient', 'Gia vị', null, null, 0, 0, 0, 0, 0, 0, 39000, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('ca-phe-den', 'Cà phê đen pha', 'ingredient', 'Đồ uống', 'ly', 200, 2, 0.2, 0.3, 0, 0, 0, 3, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('pho-bo', 'Phở bò', 'dish', 'Món nước', 'tô', 353, 137.1, 7.2, 22.5, 1.9, 0.1, 0, 134, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('pho-ga', 'Phở gà', 'dish', 'Món nước', 'tô', 360, 150.5, 7.4, 22.1, 3.4, 0.1, 0, 136, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('bun-bo-hue', 'Bún bò Huế', 'dish', 'Món nước', 'tô', 332, 139.1, 8, 21.1, 2.4, 0, 0, 214, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('com-tam-suon', 'Cơm tấm sườn', 'dish', 'Cơm', 'phần', 413, 131.8, 7.3, 17.4, 3.3, 0.3, 0, 171, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('com-ga', 'Cơm gà', 'dish', 'Cơm', 'phần', 380, 158.4, 8.3, 18.6, 5.4, 0.3, 0, 149, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('com-trung', 'Cơm trứng', 'dish', 'Cơm', 'phần', 269, 150.9, 5, 21.2, 4.7, 0.3, 0, 149, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('banh-mi-thit', 'Bánh mì thịt', 'dish', 'Món khô', 'ổ', 188, 201.8, 10.7, 28.4, 4.5, 0.1, 0, 274, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('goi-cuon', 'Gỏi cuốn', 'dish', 'Món khô', 'cuốn', 170, 102.1, 9.4, 12.1, 1.6, 0.4, 0, 59, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('canh-rau-muong', 'Canh rau muống', 'dish', 'Canh', 'bát', 187, 45, 5.2, 2.7, 1.5, 1.4, 0, 266, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('rau-muong-xao-toi', 'Rau muống xào tỏi', 'dish', 'Món xào', 'đĩa', 164, 71.4, 2.7, 3.8, 5.2, 1.7, 0, 37, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('dau-hu-chien', 'Đậu hũ chiên', 'dish', 'Món chiên', 'phần', 160, 145.3, 8.4, 2.8, 11.4, 0, 0, 9, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('trung-chien', 'Trứng chiên', 'dish', 'Món chiên', 'phần', 108, 220.3, 12, 0.9, 18.1, 0, 0, 120, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('ca-thu-chien', 'Cá thu chiên', 'dish', 'Món chiên', 'phần', 130, 203, 17.5, 0, 14.6, 0, 0, 74, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('khoai-tay-chien', 'Khoai tây chiên', 'dish', 'Món chiên', 'phần', 165, 165.4, 1.8, 18.2, 9.2, 1.3, 0, 5, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('khoai-lang-luoc', 'Khoai lang luộc', 'dish', 'Món luộc', 'củ', 150, 119, 1.1, 27.9, 0.2, 1.3, 0, 11, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('sua-chua-chuoi', 'Sữa chua chuối', 'dish', 'Bữa phụ', 'hộp', 160, 74.5, 3.1, 11.8, 1.7, 1, 0, 29, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('ca-phe-sua-da', 'Cà phê sữa đá', 'dish', 'Đồ uống', 'ly', 175, 47.6, 1.3, 8, 1.2, 0, 0, 18, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('sinh-to-chuoi-sua', 'Sinh tố chuối sữa', 'dish', 'Đồ uống', 'ly', 270, 77, 2.4, 12.6, 2, 1.2, 0, 25, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('com-rang-trung', 'Cơm rang trứng', 'dish', 'Cơm', 'đĩa', 333, 150.3, 4.5, 21.5, 4.7, 0.3, 0, 146, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('com-ga-xoi-mo', 'Cơm gà', 'dish', 'Cơm', 'phần', 413, 155.5, 7.7, 17.3, 5.9, 0.3, 0, 119, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('com-thit-kho-trung', 'Cơm thịt kho trứng', 'dish', 'Cơm', 'phần', 420, 146.5, 7.8, 18.2, 4.3, 0.2, 0, 218, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('com-ca-kho', 'Cơm cá kho', 'dish', 'Cơm', 'phần', 397, 124.8, 6.7, 18.9, 2.2, 0.3, 0, 219, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('com-chien-ca', 'Cơm chiên cá', 'dish', 'Cơm', 'đĩa', 438, 132.1, 6.7, 16.8, 3.9, 0.4, 0, 36, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('com-tam-day-du', 'Cơm tấm sườn bì chả', 'dish', 'Cơm', 'phần', 486, 136.2, 8.5, 14.8, 4.4, 0.2, 0, 192, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('com-rau-luoc-trung', 'Cơm rau luộc trứng', 'dish', 'Cơm', 'phần', 407, 93.9, 4, 15.1, 1.7, 0.9, 0, 321, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('bun-cha-ca', 'Bún chả cá', 'dish', 'Món nước', 'tô', 403, 118.3, 6.7, 17.8, 2.1, 0.1, 0, 182, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('bun-rieu-chay', 'Bún riêu chay', 'dish', 'Món nước', 'tô', 418, 103, 4.1, 18.3, 1.5, 0.2, 0, 161, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('mi-ga', 'Mì gà', 'dish', 'Món nước', 'tô', 198, 297.1, 14.1, 25.8, 15, 0.1, 0, 679, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('hu-tieu-nuoc', 'Hủ tiếu nước', 'dish', 'Món nước', 'tô', 368, 129.3, 8.6, 19.2, 1.7, 0, 0, 211, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('chao-ga', 'Cháo gà', 'dish', 'Món nước', 'bát', 177, 231.3, 14.4, 26.2, 7.8, 0.4, 0, 708, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('chao-ca-basa', 'Cháo cá', 'dish', 'Món nước', 'bát', 172, 171.9, 12.1, 26.8, 1.8, 0.4, 0, 494, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('canh-chua-ca-thu', 'Canh chua cá thu', 'dish', 'Canh', 'bát', 275, 81.3, 8.8, 3.8, 3.4, 0.5, 0, 325, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('canh-cai-ngot-thit', 'Canh cải ngọt thịt', 'dish', 'Canh', 'bát', 217, 51, 6.5, 1.7, 1.9, 0.8, 0, 576, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('canh-ca-rot-khoai-tay', 'Canh cà rốt khoai tây', 'dish', 'Canh', 'bát', 252, 79.6, 5, 11.4, 1.4, 1.5, 0, 351, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('canh-dau-hu-ca-chua', 'Canh đậu hũ cà chua', 'dish', 'Canh', 'bát', 235, 69.4, 4.9, 3.5, 4.2, 0.5, 0, 342, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('rau-muong-luoc', 'Rau muống luộc', 'dish', 'Rau', 'đĩa', 207, 25, 2.7, 3, 0.3, 1.7, 0, 605, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('cai-ngot-xao-toi', 'Cải ngọt xào tỏi', 'dish', 'Rau', 'đĩa', 221, 53.3, 1.9, 3.3, 3.8, 1.2, 0, 205, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('nom-ca-rot-dua-leo', 'Nộm cà rốt dưa leo', 'dish', 'Rau', 'đĩa', 276, 81.6, 2.7, 10.4, 3.4, 1.9, 0, 255, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('dau-hu-sot-ca-chua', 'Đậu hũ sốt cà chua', 'dish', 'Món mặn', 'phần', 294, 82.6, 5, 3.5, 5.6, 0.5, 0, 170, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('thit-heo-kho', 'Thịt heo kho', 'dish', 'Món mặn', 'phần', 183, 162.3, 16.1, 5.4, 8.1, 0, 0, 689, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('ca-basa-kho-to', 'Cá basa kho tộ', 'dish', 'Món mặn', 'phần', 213, 115.1, 14, 4.7, 4.5, 0, 0, 604, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('ca-thu-hap', 'Cá thu hấp', 'dish', 'Món mặn', 'phần', 208, 116.2, 14.3, 2.4, 5.5, 0.5, 0, 371, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('tom-rang-nuoc-mam', 'Tôm rang nước mắm', 'dish', 'Món mặn', 'phần', 176, 124.3, 15.8, 4.7, 4.7, 0.1, 0, 574, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('ga-nuong', 'Gà nướng', 'dish', 'Món mặn', 'phần', 211, 212.7, 17.8, 5, 13.6, 0.1, 0, 432, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('bo-xao-cai-ngot', 'Bò xào cải ngọt', 'dish', 'Món mặn', 'phần', 290, 85.8, 9.8, 1.9, 4.4, 0.7, 0, 203, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('banh-mi-trung', 'Bánh mì trứng', 'dish', 'Bánh mì', 'ổ', 238, 202.4, 9.2, 22.9, 7.6, 0.1, 0, 356, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('banh-mi-ca', 'Bánh mì cá', 'dish', 'Bánh mì', 'ổ', 265, 156, 9.5, 21.2, 3.4, 0.4, 0, 212, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('banh-mi-thit-nuong', 'Bánh mì thịt nướng', 'dish', 'Bánh mì', 'ổ', 272, 161.5, 10.5, 22.2, 3, 0.4, 0, 436, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('xoi-dau-phong', 'Xôi đậu phộng', 'dish', 'Xôi', 'phần', 157, 401.1, 11, 61.3, 12.4, 1.8, 0, 509, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('xoi-ga', 'Xôi gà', 'dish', 'Xôi', 'phần', 227, 289.3, 13.1, 40.3, 8.5, 0.5, 0, 382, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('khoai-tay-nghien-sua', 'Khoai tây nghiền sữa', 'dish', 'Món phụ', 'phần', 270, 108.3, 2.2, 15.9, 3.8, 1, 0, 303, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('khoai-lang-nuong', 'Khoai lang nướng', 'dish', 'Món phụ', 'củ', 200, 119, 1.1, 27.9, 0.2, 1.3, 0, 11, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('trung-luoc', 'Trứng luộc', 'dish', 'Món phụ', 'phần', 101, 164.4, 12.9, 1, 11.5, 0, 0, 515, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('sua-chua-trai-cay', 'Sữa chua trái cây', 'dish', 'Tráng miệng', 'ly', 220, 72.5, 2.5, 13.1, 1.3, 1.4, 0, 21, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('sinh-to-tao-sua', 'Sinh tố táo sữa', 'dish', 'Đồ uống', 'ly', 300, 56.5, 1.8, 9.3, 1.7, 1.2, 0, 23, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('dau-phong-rang', 'Đậu phộng rang', 'dish', 'Món phụ', 'phần', 51, 561.8, 25.3, 15.7, 43.6, 5.4, 0, 773, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('goi-cuon-tom-thit', 'Gỏi cuốn tôm thịt', 'dish', 'Món cuốn', 'cuốn', 263, 119, 10.6, 9.2, 4.2, 0.7, 0, 293, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('bun-cha', 'Bún chả', 'dish', 'Món khô', 'phần', 425, 128.2, 7.4, 17, 3.1, 0.3, 0, 211, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts')
on conflict (slug) do update set
    name_vi = excluded.name_vi,
    kind = excluded.kind,
    category = excluded.category,
    serving_name = excluded.serving_name,
    serving_grams = excluded.serving_grams,
    kcal_per_100g = excluded.kcal_per_100g,
    protein_g = excluded.protein_g,
    carb_g = excluded.carb_g,
    fat_g = excluded.fat_g,
    fiber_g = excluded.fiber_g,
    sugar_g = excluded.sugar_g,
    sodium_mg = excluded.sodium_mg,
    source_ref = excluded.source_ref
;

-- 2. Bí danh tên món (biến thể địa phương, cách gọi khác)
with alias_seed (slug, alias) as (
  values
  ('com-trang', 'cơm'),
  ('com-trang', 'com'),
  ('thit-bo-nac', 'bò'),
  ('thit-bo-nac', 'bo'),
  ('thit-heo-nac', 'thịt lợn nạc'),
  ('thit-heo-nac', 'heo nạc'),
  ('thit-ga-ta', 'gà'),
  ('thit-ga-ta', 'ga'),
  ('trung-ga', 'trứng'),
  ('trung-ga', 'trung ga'),
  ('tom-tuoi', 'tôm'),
  ('tom-tuoi', 'tom'),
  ('dau-hu', 'đậu phụ'),
  ('dau-hu', 'tau hu'),
  ('dau-phong', 'lạc'),
  ('dau-phong', 'dau phong rang'),
  ('sua-chua-khong-duong', 'yaourt'),
  ('sua-chua-khong-duong', 'sua chua'),
  ('dua-leo', 'dưa chuột'),
  ('hanh-la', 'hành'),
  ('hanh-la', 'hanh la'),
  ('chuoi-tieu', 'chuối'),
  ('chuoi-tieu', 'chuoi'),
  ('tao-tay', 'táo'),
  ('tao-tay', 'tao'),
  ('duong-trang', 'đường'),
  ('duong-trang', 'duong'),
  ('ca-phe-den', 'cà phê'),
  ('ca-phe-den', 'ca phe'),
  ('ca-phe-den', 'cf'),
  ('pho-bo', 'pho'),
  ('pho-bo', 'phở'),
  ('pho-bo', 'pho bo tai'),
  ('pho-ga', 'pho ga'),
  ('bun-bo-hue', 'bun bo'),
  ('bun-bo-hue', 'bún bò'),
  ('com-tam-suon', 'com tam'),
  ('com-tam-suon', 'cơm tấm'),
  ('com-ga', 'com ga'),
  ('com-trung', 'com trung'),
  ('com-trung', 'cơm rang trứng'),
  ('banh-mi-thit', 'banh mi'),
  ('banh-mi-thit', 'bánh mì'),
  ('goi-cuon', 'goi cuon'),
  ('goi-cuon', 'gỏi cuốn'),
  ('goi-cuon', 'summer roll'),
  ('canh-rau-muong', 'canh rau muong'),
  ('canh-rau-muong', 'canh rau'),
  ('rau-muong-xao-toi', 'rau muong xao toi'),
  ('rau-muong-xao-toi', 'rau xao toi'),
  ('dau-hu-chien', 'dau hu chien'),
  ('dau-hu-chien', 'đậu phụ rán'),
  ('trung-chien', 'trung chien'),
  ('trung-chien', 'trứng rán'),
  ('ca-thu-chien', 'ca thu chien'),
  ('khoai-tay-chien', 'khoai tay chien'),
  ('khoai-tay-chien', 'french fries'),
  ('khoai-lang-luoc', 'khoai lang luoc'),
  ('sua-chua-chuoi', 'sua chua chuoi'),
  ('sua-chua-chuoi', 'yogurt chuối'),
  ('ca-phe-sua-da', 'ca phe sua da'),
  ('ca-phe-sua-da', 'cà phê sữa'),
  ('sinh-to-chuoi-sua', 'sinh to chuoi'),
  ('sinh-to-chuoi-sua', 'sinh tố chuối'),
  ('com-rang-trung', 'com rang'),
  ('com-rang-trung', 'cơm chiên trứng'),
  ('com-ga-xoi-mo', 'com ga'),
  ('com-ga-xoi-mo', 'cơm gà xối mỡ'),
  ('com-thit-kho-trung', 'com thit kho'),
  ('com-thit-kho-trung', 'cơm thịt kho'),
  ('com-ca-kho', 'com ca kho'),
  ('com-ca-kho', 'cơm cá basa kho'),
  ('com-chien-ca', 'com chien ca'),
  ('com-chien-ca', 'cơm rang cá'),
  ('com-tam-day-du', 'com tam day du'),
  ('com-tam-day-du', 'cơm tấm đầy đủ'),
  ('com-rau-luoc-trung', 'com rau trung'),
  ('com-rau-luoc-trung', 'cơm rau luộc'),
  ('bun-cha-ca', 'bun cha ca'),
  ('bun-cha-ca', 'bún chả cá Nha Trang'),
  ('bun-rieu-chay', 'bun rieu'),
  ('bun-rieu-chay', 'bún riêu'),
  ('mi-ga', 'mi ga'),
  ('mi-ga', 'mì gà trứng'),
  ('hu-tieu-nuoc', 'hu tieu'),
  ('hu-tieu-nuoc', 'hủ tiếu'),
  ('chao-ga', 'chao ga'),
  ('chao-ga', 'cháo gà ta'),
  ('chao-ca-basa', 'chao ca'),
  ('chao-ca-basa', 'cháo cá basa'),
  ('canh-chua-ca-thu', 'canh chua ca'),
  ('canh-chua-ca-thu', 'canh chua cá'),
  ('canh-cai-ngot-thit', 'canh cai ngot'),
  ('canh-cai-ngot-thit', 'canh cải thịt'),
  ('canh-ca-rot-khoai-tay', 'canh ca rot'),
  ('canh-ca-rot-khoai-tay', 'canh khoai tây cà rốt'),
  ('canh-dau-hu-ca-chua', 'canh dau hu'),
  ('canh-dau-hu-ca-chua', 'canh đậu hũ'),
  ('rau-muong-luoc', 'rau muong luoc'),
  ('rau-muong-luoc', 'rau luộc'),
  ('cai-ngot-xao-toi', 'cai ngot xao toi'),
  ('cai-ngot-xao-toi', 'cải xào tỏi'),
  ('nom-ca-rot-dua-leo', 'nom'),
  ('nom-ca-rot-dua-leo', 'nộm rau'),
  ('nom-ca-rot-dua-leo', 'salad dưa leo'),
  ('dau-hu-sot-ca-chua', 'dau hu sot ca'),
  ('dau-hu-sot-ca-chua', 'đậu hũ chiên sốt cà'),
  ('thit-heo-kho', 'thit kho'),
  ('thit-heo-kho', 'thịt kho tàu'),
  ('ca-basa-kho-to', 'ca kho to'),
  ('ca-basa-kho-to', 'cá kho'),
  ('ca-thu-hap', 'ca thu hap'),
  ('ca-thu-hap', 'cá hấp'),
  ('tom-rang-nuoc-mam', 'tom rang'),
  ('tom-rang-nuoc-mam', 'tôm rang'),
  ('ga-nuong', 'ga nuong'),
  ('ga-nuong', 'gà nướng mật ong'),
  ('bo-xao-cai-ngot', 'bo xao'),
  ('bo-xao-cai-ngot', 'bò xào rau'),
  ('banh-mi-trung', 'banh mi trung'),
  ('banh-mi-trung', 'bánh mì ốp la'),
  ('banh-mi-ca', 'banh mi ca'),
  ('banh-mi-ca', 'bánh mì cá hộp'),
  ('banh-mi-thit-nuong', 'banh mi thit'),
  ('banh-mi-thit-nuong', 'bánh mì thịt'),
  ('xoi-dau-phong', 'xoi dau'),
  ('xoi-dau-phong', 'xôi đậu'),
  ('xoi-ga', 'xoi ga'),
  ('xoi-ga', 'xôi gà ta'),
  ('khoai-tay-nghien-sua', 'khoai tay nghien'),
  ('khoai-tay-nghien-sua', 'purée khoai tây'),
  ('khoai-lang-nuong', 'khoai lang nuong'),
  ('khoai-lang-nuong', 'khoai nướng'),
  ('trung-luoc', 'trung luoc'),
  ('trung-luoc', 'trứng gà luộc'),
  ('sua-chua-trai-cay', 'sua chua trai cay'),
  ('sua-chua-trai-cay', 'sữa chua hoa quả'),
  ('sinh-to-tao-sua', 'sinh to tao'),
  ('sinh-to-tao-sua', 'sinh tố táo'),
  ('dau-phong-rang', 'dau phong'),
  ('dau-phong-rang', 'đậu phộng'),
  ('goi-cuon-tom-thit', 'goi cuon tom'),
  ('goi-cuon-tom-thit', 'gỏi cuốn tôm'),
  ('bun-cha', 'bun cha'),
  ('bun-cha', 'bún chả Hà Nội'),
  ('bun-cha', 'bun cha ha noi')
)
insert into public.food_aliases (food_id, alias)
select f.id, s.alias
from alias_seed s
join public.foods f on f.slug = s.slug
on conflict (food_id, alias) do nothing;

-- 3. Thành phần của món
with component_seed (dish_slug, ingredient_slug, grams) as (
  values
  ('pho-bo', 'pho-tuoi', 250),
  ('pho-bo', 'thit-bo-nac', 80),
  ('pho-bo', 'hanh-la', 15),
  ('pho-bo', 'nuoc-mam', 5),
  ('pho-bo', 'dau-an', 3),
  ('pho-ga', 'pho-tuoi', 250),
  ('pho-ga', 'thit-ga-ta', 90),
  ('pho-ga', 'hanh-la', 15),
  ('pho-ga', 'nuoc-mam', 5),
  ('bun-bo-hue', 'pho-tuoi', 220),
  ('bun-bo-hue', 'thit-bo-nac', 90),
  ('bun-bo-hue', 'hanh-la', 10),
  ('bun-bo-hue', 'nuoc-mam', 8),
  ('bun-bo-hue', 'dau-an', 4),
  ('com-tam-suon', 'com-trang', 250),
  ('com-tam-suon', 'thit-heo-nac', 120),
  ('com-tam-suon', 'dua-leo', 30),
  ('com-tam-suon', 'dau-an', 5),
  ('com-tam-suon', 'nuoc-mam', 8),
  ('com-ga', 'com-trang', 250),
  ('com-ga', 'thit-ga-ta', 120),
  ('com-ga', 'dau-an', 4),
  ('com-ga', 'nuoc-mam', 6),
  ('com-trung', 'com-trang', 200),
  ('com-trung', 'trung-ga', 60),
  ('com-trung', 'dau-an', 5),
  ('com-trung', 'nuoc-mam', 4),
  ('banh-mi-thit', 'banh-mi', 100),
  ('banh-mi-thit', 'thit-heo-nac', 60),
  ('banh-mi-thit', 'dua-leo', 25),
  ('banh-mi-thit', 'dau-an', 3),
  ('goi-cuon', 'pho-tuoi', 60),
  ('goi-cuon', 'tom-tuoi', 40),
  ('goi-cuon', 'rau-muong', 40),
  ('goi-cuon', 'thit-heo-nac', 30),
  ('canh-rau-muong', 'rau-muong', 150),
  ('canh-rau-muong', 'tom-tuoi', 30),
  ('canh-rau-muong', 'nuoc-mam', 5),
  ('canh-rau-muong', 'dau-an', 2),
  ('rau-muong-xao-toi', 'rau-muong', 150),
  ('rau-muong-xao-toi', 'toi', 6),
  ('rau-muong-xao-toi', 'dau-an', 8),
  ('dau-hu-chien', 'dau-hu', 150),
  ('dau-hu-chien', 'dau-an', 10),
  ('trung-chien', 'trung-ga', 100),
  ('trung-chien', 'dau-an', 8),
  ('ca-thu-chien', 'ca-thu', 120),
  ('ca-thu-chien', 'dau-an', 10),
  ('khoai-tay-chien', 'khoai-tay', 150),
  ('khoai-tay-chien', 'dau-an', 15),
  ('khoai-lang-luoc', 'khoai-lang', 150),
  ('sua-chua-chuoi', 'sua-chua-khong-duong', 100),
  ('sua-chua-chuoi', 'chuoi-tieu', 60),
  ('ca-phe-sua-da', 'ca-phe-den', 150),
  ('ca-phe-sua-da', 'sua-dac', 25),
  ('sinh-to-chuoi-sua', 'chuoi-tieu', 120),
  ('sinh-to-chuoi-sua', 'sua-tuoi-khong-duong', 150),
  ('com-rang-trung', 'com-trang', 250),
  ('com-rang-trung', 'trung-ga', 60),
  ('com-rang-trung', 'hanh-la', 10),
  ('com-rang-trung', 'dau-an', 8),
  ('com-rang-trung', 'nuoc-mam', 5),
  ('com-ga-xoi-mo', 'com-trang', 250),
  ('com-ga-xoi-mo', 'thit-ga-ta', 120),
  ('com-ga-xoi-mo', 'dua-leo', 30),
  ('com-ga-xoi-mo', 'dau-an', 8),
  ('com-ga-xoi-mo', 'nuoc-mam', 5),
  ('com-thit-kho-trung', 'com-trang', 250),
  ('com-thit-kho-trung', 'thit-heo-nac', 100),
  ('com-thit-kho-trung', 'trung-ga', 50),
  ('com-thit-kho-trung', 'nuoc-mam', 10),
  ('com-thit-kho-trung', 'duong-trang', 5),
  ('com-thit-kho-trung', 'dau-an', 5),
  ('com-ca-kho', 'com-trang', 250),
  ('com-ca-kho', 'ca-basa', 120),
  ('com-ca-kho', 'nuoc-mam', 10),
  ('com-ca-kho', 'duong-trang', 4),
  ('com-ca-kho', 'dau-an', 5),
  ('com-ca-kho', 'hanh-la', 8),
  ('com-chien-ca', 'com-trang', 250),
  ('com-chien-ca', 'ca-basa', 100),
  ('com-chien-ca', 'trung-ga', 50),
  ('com-chien-ca', 'ca-rot', 30),
  ('com-chien-ca', 'dau-an', 8),
  ('com-tam-day-du', 'com-trang', 250),
  ('com-tam-day-du', 'thit-heo-nac', 150),
  ('com-tam-day-du', 'trung-ga', 40),
  ('com-tam-day-du', 'dua-leo', 30),
  ('com-tam-day-du', 'nuoc-mam', 10),
  ('com-tam-day-du', 'dau-an', 6),
  ('com-rau-luoc-trung', 'com-trang', 200),
  ('com-rau-luoc-trung', 'rau-muong', 150),
  ('com-rau-luoc-trung', 'trung-ga', 50),
  ('com-rau-luoc-trung', 'muoi-an', 2),
  ('com-rau-luoc-trung', 'nuoc-mam', 5),
  ('bun-cha-ca', 'pho-tuoi', 220),
  ('bun-cha-ca', 'ca-basa', 120),
  ('bun-cha-ca', 'ca-chua', 40),
  ('bun-cha-ca', 'hanh-la', 10),
  ('bun-cha-ca', 'nuoc-mam', 8),
  ('bun-cha-ca', 'dau-an', 5),
  ('bun-rieu-chay', 'pho-tuoi', 220),
  ('bun-rieu-chay', 'dau-hu', 100),
  ('bun-rieu-chay', 'ca-chua', 80),
  ('bun-rieu-chay', 'hanh-la', 10),
  ('bun-rieu-chay', 'nuoc-mam', 8),
  ('mi-ga', 'mi-an-lien', 80),
  ('mi-ga', 'thit-ga-ta', 100),
  ('mi-ga', 'hanh-la', 10),
  ('mi-ga', 'nuoc-mam', 5),
  ('mi-ga', 'dau-an', 3),
  ('hu-tieu-nuoc', 'pho-tuoi', 220),
  ('hu-tieu-nuoc', 'thit-heo-nac', 80),
  ('hu-tieu-nuoc', 'tom-tuoi', 50),
  ('hu-tieu-nuoc', 'hanh-la', 10),
  ('hu-tieu-nuoc', 'nuoc-mam', 8),
  ('chao-ga', 'gao-te', 60),
  ('chao-ga', 'thit-ga-ta', 100),
  ('chao-ga', 'hanh-la', 10),
  ('chao-ga', 'nuoc-mam', 5),
  ('chao-ga', 'muoi-an', 2),
  ('chao-ca-basa', 'gao-te', 60),
  ('chao-ca-basa', 'ca-basa', 100),
  ('chao-ca-basa', 'hanh-la', 10),
  ('chao-ca-basa', 'muoi-an', 2),
  ('canh-chua-ca-thu', 'ca-thu', 120),
  ('canh-chua-ca-thu', 'ca-chua', 80),
  ('canh-chua-ca-thu', 'dua-leo', 50),
  ('canh-chua-ca-thu', 'hanh-la', 10),
  ('canh-chua-ca-thu', 'nuoc-mam', 10),
  ('canh-chua-ca-thu', 'duong-trang', 5),
  ('canh-cai-ngot-thit', 'cai-ngot', 150),
  ('canh-cai-ngot-thit', 'thit-heo-nac', 60),
  ('canh-cai-ngot-thit', 'muoi-an', 2),
  ('canh-cai-ngot-thit', 'nuoc-mam', 5),
  ('canh-ca-rot-khoai-tay', 'ca-rot', 100),
  ('canh-ca-rot-khoai-tay', 'khoai-tay', 100),
  ('canh-ca-rot-khoai-tay', 'thit-heo-nac', 50),
  ('canh-ca-rot-khoai-tay', 'muoi-an', 2),
  ('canh-dau-hu-ca-chua', 'dau-hu', 120),
  ('canh-dau-hu-ca-chua', 'ca-chua', 100),
  ('canh-dau-hu-ca-chua', 'hanh-la', 10),
  ('canh-dau-hu-ca-chua', 'muoi-an', 2),
  ('canh-dau-hu-ca-chua', 'dau-an', 3),
  ('rau-muong-luoc', 'rau-muong', 200),
  ('rau-muong-luoc', 'muoi-an', 2),
  ('rau-muong-luoc', 'nuoc-mam', 5),
  ('cai-ngot-xao-toi', 'cai-ngot', 200),
  ('cai-ngot-xao-toi', 'toi', 8),
  ('cai-ngot-xao-toi', 'dau-an', 8),
  ('cai-ngot-xao-toi', 'nuoc-mam', 5),
  ('nom-ca-rot-dua-leo', 'ca-rot', 100),
  ('nom-ca-rot-dua-leo', 'dua-leo', 100),
  ('nom-ca-rot-dua-leo', 'dau-phong', 20),
  ('nom-ca-rot-dua-leo', 'duong-trang', 8),
  ('nom-ca-rot-dua-leo', 'nuoc-mam', 8),
  ('nom-ca-rot-dua-leo', 'tao-tay', 40),
  ('dau-hu-sot-ca-chua', 'dau-hu', 150),
  ('dau-hu-sot-ca-chua', 'ca-chua', 120),
  ('dau-hu-sot-ca-chua', 'hanh-la', 10),
  ('dau-hu-sot-ca-chua', 'dau-an', 8),
  ('dau-hu-sot-ca-chua', 'nuoc-mam', 6),
  ('thit-heo-kho', 'thit-heo-nac', 150),
  ('thit-heo-kho', 'nuoc-mam', 15),
  ('thit-heo-kho', 'duong-trang', 8),
  ('thit-heo-kho', 'toi', 5),
  ('thit-heo-kho', 'dau-an', 5),
  ('ca-basa-kho-to', 'ca-basa', 180),
  ('ca-basa-kho-to', 'nuoc-mam', 15),
  ('ca-basa-kho-to', 'duong-trang', 8),
  ('ca-basa-kho-to', 'toi', 5),
  ('ca-basa-kho-to', 'dau-an', 5),
  ('ca-thu-hap', 'ca-thu', 150),
  ('ca-thu-hap', 'hanh-la', 15),
  ('ca-thu-hap', 'toi', 5),
  ('ca-thu-hap', 'nuoc-mam', 8),
  ('ca-thu-hap', 'ca-rot', 30),
  ('tom-rang-nuoc-mam', 'tom-tuoi', 150),
  ('tom-rang-nuoc-mam', 'nuoc-mam', 10),
  ('tom-rang-nuoc-mam', 'duong-trang', 5),
  ('tom-rang-nuoc-mam', 'toi', 5),
  ('tom-rang-nuoc-mam', 'dau-an', 6),
  ('ga-nuong', 'thit-ga-ta', 180),
  ('ga-nuong', 'duong-trang', 8),
  ('ga-nuong', 'nuoc-mam', 10),
  ('ga-nuong', 'toi', 8),
  ('ga-nuong', 'dau-an', 5),
  ('bo-xao-cai-ngot', 'thit-bo-nac', 120),
  ('bo-xao-cai-ngot', 'cai-ngot', 150),
  ('bo-xao-cai-ngot', 'toi', 6),
  ('bo-xao-cai-ngot', 'dau-an', 8),
  ('bo-xao-cai-ngot', 'nuoc-mam', 6),
  ('banh-mi-trung', 'banh-mi', 100),
  ('banh-mi-trung', 'trung-ga', 100),
  ('banh-mi-trung', 'dua-leo', 30),
  ('banh-mi-trung', 'dau-an', 5),
  ('banh-mi-trung', 'nuoc-mam', 3),
  ('banh-mi-ca', 'banh-mi', 100),
  ('banh-mi-ca', 'ca-basa', 100),
  ('banh-mi-ca', 'ca-rot', 30),
  ('banh-mi-ca', 'dua-leo', 30),
  ('banh-mi-ca', 'dau-an', 5),
  ('banh-mi-thit-nuong', 'banh-mi', 100),
  ('banh-mi-thit-nuong', 'thit-heo-nac', 100),
  ('banh-mi-thit-nuong', 'ca-rot', 30),
  ('banh-mi-thit-nuong', 'dua-leo', 30),
  ('banh-mi-thit-nuong', 'nuoc-mam', 8),
  ('banh-mi-thit-nuong', 'duong-trang', 4),
  ('xoi-dau-phong', 'gao-te', 120),
  ('xoi-dau-phong', 'dau-phong', 30),
  ('xoi-dau-phong', 'muoi-an', 2),
  ('xoi-dau-phong', 'dau-an', 5),
  ('xoi-ga', 'gao-te', 120),
  ('xoi-ga', 'thit-ga-ta', 100),
  ('xoi-ga', 'dau-an', 5),
  ('xoi-ga', 'muoi-an', 2),
  ('khoai-tay-nghien-sua', 'khoai-tay', 200),
  ('khoai-tay-nghien-sua', 'sua-tuoi-khong-duong', 60),
  ('khoai-tay-nghien-sua', 'dau-an', 8),
  ('khoai-tay-nghien-sua', 'muoi-an', 2),
  ('khoai-lang-nuong', 'khoai-lang', 200),
  ('trung-luoc', 'trung-ga', 100),
  ('trung-luoc', 'muoi-an', 1),
  ('sua-chua-trai-cay', 'sua-chua-khong-duong', 100),
  ('sua-chua-trai-cay', 'chuoi-tieu', 80),
  ('sua-chua-trai-cay', 'tao-tay', 40),
  ('sinh-to-tao-sua', 'tao-tay', 150),
  ('sinh-to-tao-sua', 'sua-tuoi-khong-duong', 150),
  ('dau-phong-rang', 'dau-phong', 50),
  ('dau-phong-rang', 'muoi-an', 1),
  ('goi-cuon-tom-thit', 'pho-tuoi', 60),
  ('goi-cuon-tom-thit', 'tom-tuoi', 60),
  ('goi-cuon-tom-thit', 'thit-heo-nac', 50),
  ('goi-cuon-tom-thit', 'rau-muong', 40),
  ('goi-cuon-tom-thit', 'dua-leo', 30),
  ('goi-cuon-tom-thit', 'nuoc-mam', 8),
  ('goi-cuon-tom-thit', 'dau-phong', 15),
  ('bun-cha', 'pho-tuoi', 200),
  ('bun-cha', 'thit-heo-nac', 120),
  ('bun-cha', 'rau-muong', 50),
  ('bun-cha', 'dua-leo', 30),
  ('bun-cha', 'nuoc-mam', 10),
  ('bun-cha', 'duong-trang', 5),
  ('bun-cha', 'toi', 5),
  ('bun-cha', 'dau-an', 5)
)
insert into public.dish_components (dish_id, ingredient_id, grams)
select d.id, i.id, s.grams
from component_seed s
join public.foods d on d.slug = s.dish_slug
join public.foods i on i.slug = s.ingredient_slug
on conflict (dish_id, ingredient_id) do update set grams = excluded.grams;

-- 4. Tính lại chỉ số của món từ thành phần vừa nạp.
--    Bước này khiến CSDL trở thành nguồn chân lý: dù file trên có sai sót,
--    con số cuối cùng vẫn nhất quán với thành phần.
select public.recompute_dish_nutrients(id) from public.foods where kind = 'dish';

-- 5. Danh mục bài tập
--    MET là nguồn chân lý để tính kcal đốt của buổi tập; không được để model tự đoán.
insert into public.exercises (slug, name_vi, muscle_group, equipment, level, measure, met, contraindications, cue, source_ref)
values
  ('squat-bodyweight', 'Squat không tạ', 'legs', 'bodyweight', 'beginner', 'reps', 5, '{}'::public.injury_area[], 'Hạ hông như ngồi xuống ghế, đầu gối hướng theo mũi chân.', 'MET theo 2011 Compendium of Physical Activities'),
  ('squat-goblet', 'Goblet squat', 'legs', 'dumbbell', 'beginner', 'reps', 5, '{}'::public.injury_area[], 'Ôm tạ trước ngực, giữ thân trên thẳng.', 'MET theo 2011 Compendium of Physical Activities'),
  ('lunge', 'Chùng chân (lunge)', 'legs', 'bodyweight', 'beginner', 'reps', 5, array['knee']::public.injury_area[], 'Bước tới, hạ gối sau gần sàn rồi đẩy về.', 'MET theo 2011 Compendium of Physical Activities'),
  ('deadlift-romanian', 'Romanian deadlift', 'glutes', 'barbell', 'intermediate', 'reps', 6, array['lower_back']::public.injury_area[], 'Đẩy hông ra sau, giữ lưng thẳng, cảm nhận căng mặt sau đùi.', 'MET theo 2011 Compendium of Physical Activities'),
  ('hip-thrust', 'Hip thrust', 'glutes', 'barbell', 'intermediate', 'reps', 5, '{}'::public.injury_area[], 'Tựa lưng trên ghế, siết mông ở đỉnh rồi hạ chậm.', 'MET theo 2011 Compendium of Physical Activities'),
  ('calf-raise', 'Nhón gót', 'legs', 'bodyweight', 'beginner', 'reps', 3.5, '{}'::public.injury_area[], 'Lên hết cỡ rồi hạ chậm, không nảy.', 'MET theo 2011 Compendium of Physical Activities'),
  ('leg-press', 'Đạp đùi máy', 'legs', 'machine', 'beginner', 'reps', 5, '{}'::public.injury_area[], 'Không khoá khớp gối ở đỉnh.', 'MET theo 2011 Compendium of Physical Activities'),
  ('push-up', 'Hít đất', 'chest', 'bodyweight', 'beginner', 'reps', 4.3, array['wrist', 'shoulder']::public.injury_area[], 'Thân người thành một đường thẳng, khuỷu tay hơi khép.', 'MET theo 2011 Compendium of Physical Activities'),
  ('bench-press', 'Đẩy ngực ghế ngang', 'chest', 'barbell', 'intermediate', 'reps', 5, array['shoulder']::public.injury_area[], 'Siết vai về sau, hạ tạ tới ngang ngực.', 'MET theo 2011 Compendium of Physical Activities'),
  ('dumbbell-shoulder-press', 'Đẩy vai tạ đơn', 'shoulders', 'dumbbell', 'beginner', 'reps', 5, array['shoulder']::public.injury_area[], 'Đẩy thẳng lên, không ưỡn lưng.', 'MET theo 2011 Compendium of Physical Activities'),
  ('lateral-raise', 'Nâng vai ngang', 'shoulders', 'dumbbell', 'beginner', 'reps', 4, '{}'::public.injury_area[], 'Nâng tới ngang vai, khuỷu hơi cong.', 'MET theo 2011 Compendium of Physical Activities'),
  ('triceps-dip', 'Chống xà kép', 'arms', 'bodyweight', 'intermediate', 'reps', 5, array['shoulder', 'wrist']::public.injury_area[], 'Hạ tới khi khuỷu vuông góc rồi đẩy lên.', 'MET theo 2011 Compendium of Physical Activities'),
  ('pull-up', 'Hít xà', 'back', 'bodyweight', 'advanced', 'reps', 8, array['shoulder', 'wrist']::public.injury_area[], 'Kéo bằng lưng, không đung đưa người.', 'MET theo 2011 Compendium of Physical Activities'),
  ('lat-pulldown', 'Kéo xô máy', 'back', 'machine', 'beginner', 'reps', 5, '{}'::public.injury_area[], 'Kéo thanh về ngực trên, siết xô ở cuối.', 'MET theo 2011 Compendium of Physical Activities'),
  ('seated-row', 'Kéo cáp ngồi', 'back', 'machine', 'beginner', 'reps', 5, '{}'::public.injury_area[], 'Giữ lưng thẳng, kéo khuỷu ra sau.', 'MET theo 2011 Compendium of Physical Activities'),
  ('band-row', 'Kéo dây kháng lực', 'back', 'band', 'beginner', 'reps', 4, '{}'::public.injury_area[], 'Siết bả vai lại với nhau ở cuối động tác.', 'MET theo 2011 Compendium of Physical Activities'),
  ('biceps-curl', 'Cuốn tay trước', 'arms', 'dumbbell', 'beginner', 'reps', 3.5, '{}'::public.injury_area[], 'Giữ khuỷu cố định, không vung người.', 'MET theo 2011 Compendium of Physical Activities'),
  ('plank', 'Plank', 'core', 'bodyweight', 'beginner', 'time', 3.5, '{}'::public.injury_area[], 'Siết bụng và mông, giữ hông không võng.', 'MET theo 2011 Compendium of Physical Activities'),
  ('dead-bug', 'Dead bug', 'core', 'bodyweight', 'beginner', 'reps', 3, '{}'::public.injury_area[], 'Giữ lưng dưới áp sàn suốt động tác.', 'MET theo 2011 Compendium of Physical Activities'),
  ('russian-twist', 'Xoay người kiểu Nga', 'core', 'bodyweight', 'intermediate', 'reps', 4, array['lower_back']::public.injury_area[], 'Xoay từ thân trên, không kéo bằng tay.', 'MET theo 2011 Compendium of Physical Activities'),
  ('hanging-leg-raise', 'Treo xà nâng chân', 'core', 'bodyweight', 'advanced', 'reps', 5, array['shoulder', 'lower_back']::public.injury_area[], 'Nâng chân có kiểm soát, không đung đưa.', 'MET theo 2011 Compendium of Physical Activities'),
  ('walking-brisk', 'Đi bộ nhanh', 'cardio', 'bodyweight', 'beginner', 'time', 4.3, '{}'::public.injury_area[], 'Đi nhanh tới mức nói được nhưng không hát được.', 'MET theo 2011 Compendium of Physical Activities'),
  ('running', 'Chạy bộ', 'cardio', 'bodyweight', 'intermediate', 'time', 9.8, array['knee', 'ankle']::public.injury_area[], 'Tiếp đất bằng giữa bàn chân, nhịp thở đều.', 'MET theo 2011 Compendium of Physical Activities'),
  ('cycling', 'Đạp xe', 'cardio', 'cardio_machine', 'beginner', 'time', 7.5, '{}'::public.injury_area[], 'Giữ nhịp đều, điều chỉnh lực cản vừa sức.', 'MET theo 2011 Compendium of Physical Activities'),
  ('rowing', 'Chèo thuyền máy', 'full_body', 'cardio_machine', 'intermediate', 'time', 7, array['lower_back']::public.injury_area[], 'Đẩy bằng chân trước, rồi mới kéo tay.', 'MET theo 2011 Compendium of Physical Activities'),
  ('jump-rope', 'Nhảy dây', 'cardio', 'bodyweight', 'intermediate', 'time', 10, array['knee', 'ankle']::public.injury_area[], 'Nhảy thấp, tiếp đất nhẹ bằng mũi chân.', 'MET theo 2011 Compendium of Physical Activities'),
  ('burpee', 'Burpee', 'full_body', 'bodyweight', 'advanced', 'time', 8, array['knee', 'lower_back', 'wrist']::public.injury_area[], 'Giữ nhịp đều, hạ xuống bằng tay chắc.', 'MET theo 2011 Compendium of Physical Activities'),
  ('mountain-climber', 'Leo núi tại chỗ', 'full_body', 'bodyweight', 'intermediate', 'time', 8, array['wrist']::public.injury_area[], 'Hông giữ thấp, đổi chân nhanh.', 'MET theo 2011 Compendium of Physical Activities'),
  ('kettlebell-swing', 'Vung tạ ấm', 'full_body', 'dumbbell', 'intermediate', 'reps', 9.8, array['lower_back']::public.injury_area[], 'Lực phát ra từ hông, tay chỉ giữ tạ.', 'MET theo 2011 Compendium of Physical Activities'),
  ('arm-circle', 'Xoay vai khởi động', 'mobility', 'bodyweight', 'beginner', 'time', 2.3, '{}'::public.injury_area[], 'Xoay chậm, tăng dần biên độ.', 'MET theo 2011 Compendium of Physical Activities'),
  ('cat-cow', 'Mèo–bò giãn cột sống', 'mobility', 'bodyweight', 'beginner', 'time', 2.3, '{}'::public.injury_area[], 'Phối hợp hơi thở với chuyển động.', 'MET theo 2011 Compendium of Physical Activities'),
  ('hip-opener', 'Giãn hông', 'mobility', 'bodyweight', 'beginner', 'time', 2.3, '{}'::public.injury_area[], 'Giữ 30 giây mỗi bên, không nảy.', 'MET theo 2011 Compendium of Physical Activities'),
  ('hamstring-stretch', 'Giãn mặt sau đùi', 'mobility', 'bodyweight', 'beginner', 'time', 2.3, '{}'::public.injury_area[], 'Giữ thẳng lưng, gập từ hông.', 'MET theo 2011 Compendium of Physical Activities')
on conflict (slug) do update set
    name_vi = excluded.name_vi,
    muscle_group = excluded.muscle_group,
    equipment = excluded.equipment,
    level = excluded.level,
    measure = excluded.measure,
    met = excluded.met,
    contraindications = excluded.contraindications,
    cue = excluded.cue,
    source_ref = excluded.source_ref
;
