-- ============================================================================
-- NutriBoost — dữ liệu món Việt
--
-- FILE NÀY ĐƯỢC SINH TỰ ĐỘNG. ĐỪNG SỬA TAY.
-- Nguồn: packages/seed/src/data/ingredients.ts và packages/seed/src/data/dishes.ts
-- Sinh lại: npm run seed -- --emit-sql
--
-- Chỉ số của món được tính từ thành phần bằng recompute_dish_nutrients() ở cuối file,
-- nên sửa một nguyên liệu sẽ tự động cập nhật mọi món dùng nguyên liệu đó.
-- ============================================================================

-- 1. Thực phẩm: nguyên liệu và món
insert into public.foods (slug, name_vi, kind, category, serving_name, serving_grams, kcal_per_100g, protein_g, carb_g, fat_g, fiber_g, sugar_g, sodium_mg, source_ref)
values
  ('gao-te', 'Gạo tẻ', 'ingredient', 'Ngũ cốc', null, null, 344, 7.9, 76.2, 1, 1, 0, 14, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('com-trang', 'Cơm trắng', 'ingredient', 'Ngũ cốc', 'bát', 200, 130, 2.7, 28.2, 0.3, 0.4, 0, 5, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('pho-tuoi', 'Bánh phở tươi', 'ingredient', 'Ngũ cốc', null, null, 143, 3.2, 31.5, 0.2, 0, 0, 12, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('banh-mi', 'Bánh mì', 'ingredient', 'Ngũ cốc', 'ổ', 100, 265, 8.6, 52.6, 1.5, 0, 0, 480, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('mi-an-lien', 'Mì ăn liền', 'ingredient', 'Ngũ cốc', 'gói', 75, 448, 9, 63, 17, 0, 0, 1100, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('khoai-tay', 'Khoai tây', 'ingredient', 'Củ', null, null, 92, 2, 20, 0.1, 1.4, 0, 6, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('khoai-lang', 'Khoai lang', 'ingredient', 'Củ', null, null, 119, 1.1, 27.9, 0.2, 1.3, 0, 11, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('thit-bo-nac', 'Thịt bò nạc', 'ingredient', 'Thịt', null, null, 118, 21, 0, 3.8, 0, 0, 60, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('thit-heo-nac', 'Thịt heo nạc', 'ingredient', 'Thịt', null, null, 139, 19, 0, 6.5, 0, 0, 55, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('thit-ga-ta', 'Thịt gà ta', 'ingredient', 'Thịt', null, null, 199, 20.3, 0, 13.1, 0, 0, 70, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('trung-ga', 'Trứng gà', 'ingredient', 'Trứng', 'quả', 50, 166, 13, 1, 11.6, 0, 0, 130, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('ca-basa', 'Cá basa', 'ingredient', 'Thủy sản', null, null, 87, 16, 0, 2.5, 0, 0, 60, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('ca-thu', 'Cá thu', 'ingredient', 'Thủy sản', null, null, 145, 19, 0, 7.5, 0, 0, 80, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('tom-tuoi', 'Tôm tươi', 'ingredient', 'Thủy sản', null, null, 90, 18, 1, 1.5, 0, 0, 150, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('dau-hu', 'Đậu hũ', 'ingredient', 'Đậu và hạt', null, null, 95, 9, 3, 5.5, 0, 0, 10, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('dau-phong', 'Đậu phộng', 'ingredient', 'Đậu và hạt', null, null, 573, 25.8, 16, 44.5, 5.5, 0, 8, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('sua-tuoi-khong-duong', 'Sữa tươi không đường', 'ingredient', 'Sữa', 'ly', 200, 61, 3.2, 4.8, 3.3, 0, 0, 45, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('sua-chua-khong-duong', 'Sữa chua không đường', 'ingredient', 'Sữa', 'hộp', 100, 61, 4.1, 5.4, 2.6, 0, 0, 45, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('sua-dac', 'Sữa đặc có đường', 'ingredient', 'Sữa', null, null, 321, 8, 54.4, 8.5, 0, 54.4, 110, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('rau-muong', 'Rau muống', 'ingredient', 'Rau', null, null, 25, 2.7, 3, 0.3, 1.8, 0, 40, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('cai-ngot', 'Cải ngọt', 'ingredient', 'Rau', null, null, 17, 1.7, 2.4, 0.2, 1.2, 0, 30, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('ca-chua', 'Cà chua', 'ingredient', 'Quả', null, null, 20, 0.6, 4.2, 0.2, 1, 0, 10, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('dua-leo', 'Dưa leo', 'ingredient', 'Quả', null, null, 16, 0.8, 2.9, 0.1, 0.7, 0, 5, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('ca-rot', 'Cà rốt', 'ingredient', 'Củ', null, null, 39, 1, 8.8, 0.2, 2.5, 4.7, 70, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('hanh-la', 'Hành lá', 'ingredient', 'Gia vị', null, null, 22, 1.3, 4.2, 0.2, 1.4, 0, 15, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('toi', 'Tỏi', 'ingredient', 'Gia vị', null, null, 127, 5.5, 28.1, 0.2, 1.8, 0, 15, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('chuoi-tieu', 'Chuối tiêu', 'ingredient', 'Quả', 'quả', 100, 97, 1.5, 22.4, 0.3, 2.6, 15, 1, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('tao-tay', 'Táo tây', 'ingredient', 'Quả', 'quả', 150, 52, 0.3, 13.8, 0.2, 2.4, 10.4, 1, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('dau-an', 'Dầu ăn', 'ingredient', 'Chất béo', 'thìa', 10, 899, 0, 0, 99.9, 0, 0, 0, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('duong-trang', 'Đường trắng', 'ingredient', 'Gia vị', 'thìa', 5, 400, 0, 99.9, 0, 0, 99.9, 1, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('nuoc-mam', 'Nước mắm', 'ingredient', 'Gia vị', 'thìa', 5, 35, 5, 3.6, 0, 0, 0, 7851, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('muoi-an', 'Muối ăn', 'ingredient', 'Gia vị', null, null, 0, 0, 0, 0, 0, 0, 39000, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('ca-phe-den', 'Cà phê đen pha', 'ingredient', 'Đồ uống', 'ly', 200, 2, 0.2, 0.3, 0, 0, 0, 3, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('bun-tuoi', 'Bún tươi', 'ingredient', 'Ngũ cốc', null, null, 110, 1.7, 25.7, 0, 0.5, 0, 10, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('gao-nep', 'Gạo nếp', 'ingredient', 'Ngũ cốc', null, null, 346, 8.6, 74.9, 1.5, 0.6, 0, 3, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('mien-dong', 'Miến dong', 'ingredient', 'Ngũ cốc', null, null, 332, 0.6, 82.2, 0.1, 1.5, 0, 10, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('banh-trang', 'Bánh tráng', 'ingredient', 'Ngũ cốc', null, null, 333, 4, 78.9, 0.2, 0.5, 0, 0, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('mi-trung', 'Mì trứng (đã luộc)', 'ingredient', 'Ngũ cốc', null, null, 138, 4.5, 25.2, 2.1, 1.2, 0, 5, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('bot-gao', 'Bột gạo', 'ingredient', 'Ngũ cốc', null, null, 359, 6.6, 82.2, 0.4, 0, 0, 5, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('bot-mi', 'Bột mì', 'ingredient', 'Ngũ cốc', null, null, 346, 11, 72.6, 1.1, 0, 0, 2, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('khoai-mi', 'Khoai mì (sắn)', 'ingredient', 'Củ', null, null, 160, 1.4, 38.1, 0.3, 1.8, 1.7, 14, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('ngo-ngot', 'Bắp Mỹ (ngô ngọt)', 'ingredient', 'Ngũ cốc', 'trái', 150, 86, 3.3, 18.7, 1.4, 2, 6.3, 15, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('yen-mach', 'Yến mạch', 'ingredient', 'Ngũ cốc', null, null, 389, 16.9, 66.3, 6.9, 10.6, 0, 2, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('nuoc-loc', 'Nước lọc', 'ingredient', 'Đồ uống', 'ly', 250, 0, 0, 0, 0, 0, 0, 0, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('thit-ba-chi', 'Thịt ba chỉ', 'ingredient', 'Thịt', null, null, 260, 16.5, 0, 21.5, 0, 0, 60, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('suon-heo', 'Sườn heo', 'ingredient', 'Thịt', null, null, 187, 17.9, 0, 12.8, 0, 0, 60, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('cha-lua', 'Chả lụa', 'ingredient', 'Thịt', 'khoanh', 50, 136, 21.5, 0, 5.5, 0, 0, 750, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('lap-xuong', 'Lạp xưởng', 'ingredient', 'Thịt', 'cây', 40, 585, 20.8, 1.7, 55, 0, 0, 1100, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('xuc-xich', 'Xúc xích', 'ingredient', 'Thịt', 'cây', 50, 290, 10.3, 4.2, 25.8, 0, 0, 1000, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('thit-vit', 'Thịt vịt', 'ingredient', 'Thịt', null, null, 267, 17.8, 0, 21.8, 0, 0, 63, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('pate', 'Pa tê gan', 'ingredient', 'Thịt', null, null, 326, 10.8, 1.6, 30.8, 0, 0, 700, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('uc-ga', 'Ức gà (bỏ da)', 'ingredient', 'Thịt', 'miếng', 150, 120, 22.5, 0, 2.6, 0, 0, 45, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('muc', 'Mực tươi', 'ingredient', 'Thủy sản', null, null, 73, 16.3, 0, 0.9, 0, 0, 44, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('cua-dong', 'Cua đồng', 'ingredient', 'Thủy sản', null, null, 87, 12.3, 2, 3.3, 0, 0, 0, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('ca-hoi', 'Cá hồi', 'ingredient', 'Thủy sản', null, null, 208, 20.4, 0, 13.4, 0, 0, 59, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('mam-tom', 'Mắm tôm', 'ingredient', 'Gia vị', 'thìa', 10, 73, 14.8, 1.5, 0.8, 0, 0, 7000, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('trung-vit', 'Trứng vịt', 'ingredient', 'Trứng', 'quả', 60, 184, 13, 1, 14.2, 0, 0, 146, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('trung-vit-lon', 'Trứng vịt lộn', 'ingredient', 'Trứng', 'quả', 60, 182, 13.6, 4, 12.4, 0, 0, 150, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('dau-xanh', 'Đậu xanh (hạt)', 'ingredient', 'Đậu và hạt', null, null, 328, 23.4, 53.1, 2.4, 4.7, 0, 15, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('dau-den', 'Đậu đen (hạt)', 'ingredient', 'Đậu và hạt', null, null, 325, 24.2, 53.3, 1.7, 4, 0, 5, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('sua-dau-nanh', 'Sữa đậu nành không đường', 'ingredient', 'Đậu và hạt', 'ly', 250, 28, 3.1, 0.4, 1.6, 0, 0, 0, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('dau-que', 'Đậu que', 'ingredient', 'Rau', null, null, 31, 1.8, 7, 0.2, 2.7, 3.3, 6, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('gia-do', 'Giá đỗ', 'ingredient', 'Rau', null, null, 43, 5.5, 5.3, 0, 1.2, 0, 6, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('bi-dao', 'Bí đao', 'ingredient', 'Rau', null, null, 12, 0.6, 2.4, 0, 1, 0, 5, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('bi-do', 'Bí đỏ', 'ingredient', 'Rau', null, null, 24, 0.3, 5.6, 0, 0.7, 0, 1, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('bap-cai', 'Bắp cải', 'ingredient', 'Rau', null, null, 29, 1.8, 5.4, 0.1, 1.6, 0, 18, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('xa-lach', 'Xà lách', 'ingredient', 'Rau', null, null, 15, 1.5, 2.2, 0.2, 0.8, 0, 10, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('hanh-tay', 'Hành tây', 'ingredient', 'Rau', null, null, 41, 1.8, 8.2, 0.1, 0.7, 0, 4, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('bong-cai-xanh', 'Bông cải xanh', 'ingredient', 'Rau', null, null, 34, 2.8, 6.6, 0.4, 2.6, 1.7, 33, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('ca-tim', 'Cà tím', 'ingredient', 'Rau', null, null, 22, 1, 4.5, 0, 1.5, 0, 2, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('xoai-chin', 'Xoài chín', 'ingredient', 'Quả', 'quả', 250, 69, 0.6, 15.9, 0.3, 0.6, 13.7, 1, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('dua-hau', 'Dưa hấu', 'ingredient', 'Quả', 'miếng', 200, 16, 1.2, 2.3, 0.2, 0.5, 0, 1, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('cam', 'Cam', 'ingredient', 'Quả', 'quả', 150, 37, 0.9, 8.4, 0, 1.4, 0, 0, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('buoi', 'Bưởi', 'ingredient', 'Quả', 'múi', 35, 30, 0.2, 7.3, 0, 0.7, 0, 1, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('thanh-long', 'Thanh long', 'ingredient', 'Quả', 'quả', 300, 60, 1.2, 12.9, 0.4, 3, 7.7, 0, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('du-du', 'Đu đủ chín', 'ingredient', 'Quả', 'miếng', 150, 35, 1, 7.7, 0, 0.6, 0, 3, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('oi', 'Ổi', 'ingredient', 'Quả', 'quả', 150, 38, 0.6, 8.9, 0, 6, 0, 2, 'Bảng thành phần dinh dưỡng thực phẩm Việt Nam 2007 (tham chiếu, cần đối chiếu)'),
  ('nho', 'Nho', 'ingredient', 'Quả', 'chùm', 100, 69, 0.7, 18.1, 0.2, 0.9, 15.5, 2, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('bo-qua', 'Bơ (quả)', 'ingredient', 'Quả', 'quả', 150, 160, 2, 8.5, 14.7, 6.7, 0.7, 7, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('sau-rieng', 'Sầu riêng', 'ingredient', 'Quả', 'múi', 50, 147, 1.5, 27.1, 5.3, 3.8, 0, 2, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('nuoc-dua', 'Nước dừa', 'ingredient', 'Đồ uống', 'trái', 300, 19, 0.7, 3.7, 0.2, 1.1, 2.6, 105, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('nuoc-cam', 'Nước cam vắt', 'ingredient', 'Đồ uống', 'ly', 250, 45, 0.7, 10.4, 0.2, 0.2, 8.4, 1, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('nuoc-mia', 'Nước mía', 'ingredient', 'Đồ uống', 'ly', 300, 60, 0.2, 15, 0, 0, 14, 5, 'Ước lượng theo nhãn dinh dưỡng / công thức pha phổ biến tại Việt Nam (cần đối chiếu)'),
  ('tra-pha', 'Trà pha (không đường)', 'ingredient', 'Đồ uống', 'ly', 250, 1, 0, 0.3, 0, 0, 0, 3, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('tran-chau', 'Trân châu (đã nấu)', 'ingredient', 'Đồ uống', 'phần', 50, 150, 0.1, 37, 0.1, 0, 8, 5, 'Ước lượng theo nhãn dinh dưỡng / công thức pha phổ biến tại Việt Nam (cần đối chiếu)'),
  ('bot-kem-beo', 'Bột kem béo', 'ingredient', 'Đồ uống', null, null, 545, 4.8, 54.9, 35.5, 0, 0, 0, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('sua-tuoi-co-duong', 'Sữa tươi có đường', 'ingredient', 'Sữa', 'hộp', 180, 75, 3, 8.4, 3.3, 0, 8.4, 45, 'Ước lượng theo nhãn dinh dưỡng / công thức pha phổ biến tại Việt Nam (cần đối chiếu)'),
  ('nuoc-ngot', 'Nước ngọt có ga', 'ingredient', 'Đồ uống', 'lon', 330, 42, 0, 10.6, 0, 0, 10.6, 4, 'Ước lượng theo nhãn dinh dưỡng / công thức pha phổ biến tại Việt Nam (cần đối chiếu)'),
  ('kem-vani', 'Kem vani', 'ingredient', 'Tráng miệng', 'cây', 60, 207, 3.5, 23.6, 11, 0.7, 21.2, 80, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('dao-ngam', 'Đào ngâm', 'ingredient', 'Quả', null, null, 74, 0.5, 19.9, 0.1, 1.3, 18.6, 6, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('nuoc-cot-dua', 'Nước cốt dừa', 'ingredient', 'Chất béo', null, null, 197, 2, 2.8, 21.3, 0, 0, 13, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('nuoc-tuong', 'Nước tương', 'ingredient', 'Gia vị', 'thìa', 5, 53, 8.1, 4.9, 0.6, 0, 0, 5493, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('mayonnaise', 'Sốt mayonnaise', 'ingredient', 'Chất béo', 'thìa', 10, 680, 1, 0.6, 74.9, 0, 0, 635, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('pho-mai', 'Phô mai cheddar', 'ingredient', 'Sữa', 'lát', 20, 403, 24.9, 1.3, 33.1, 0, 0, 621, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('tuong-ca', 'Tương cà', 'ingredient', 'Gia vị', 'thìa', 10, 101, 1, 27.4, 0.1, 0, 21.3, 907, 'USDA FoodData Central, SR Legacy (tham chiếu, cần đối chiếu)'),
  ('pho-bo', 'Phở bò', 'dish', 'Món nước', 'tô', 353, 137.1, 7.2, 22.5, 1.9, 0.1, 0, 134, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('pho-ga', 'Phở gà', 'dish', 'Món nước', 'tô', 360, 150.5, 7.4, 22.1, 3.4, 0.1, 0, 136, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('bun-bo-hue', 'Bún bò Huế', 'dish', 'Món nước', 'tô', 332, 139.1, 8, 21.1, 2.4, 0, 0, 214, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('com-tam-suon', 'Cơm tấm sườn', 'dish', 'Cơm', 'phần', 413, 131.8, 7.3, 17.4, 3.3, 0.3, 0, 171, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('com-ga', 'Cơm gà', 'dish', 'Cơm', 'phần', 380, 158.4, 8.3, 18.6, 5.4, 0.3, 0, 149, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('com-trung', 'Cơm trứng', 'dish', 'Cơm', 'phần', 269, 150.9, 5, 21.2, 4.7, 0.3, 0, 149, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('banh-mi-thit', 'Bánh mì thịt', 'dish', 'Món khô', 'ổ', 188, 201.8, 10.7, 28.4, 4.5, 0.1, 0, 274, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('goi-cuon', 'Gỏi cuốn', 'dish', 'Món khô', 'cuốn', 170, 102.1, 9.4, 12.1, 1.6, 0.4, 0, 59, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('canh-rau-muong', 'Canh rau muống', 'dish', 'Canh', 'bát', 187, 45, 5.2, 2.7, 1.5, 1.4, 0, 266, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('rau-muong-xao-toi', 'Rau muống xào tỏi', 'dish', 'Món xào', 'đĩa', 164, 71.4, 2.7, 3.8, 5.2, 1.7, 0, 37, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('dau-hu-chien', 'Đậu hũ chiên', 'dish', 'Món chiên', 'phần', 160, 145.3, 8.4, 2.8, 11.4, 0, 0, 9, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('trung-chien', 'Trứng chiên', 'dish', 'Món chiên', 'phần', 108, 220.3, 12, 0.9, 18.1, 0, 0, 120, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('ca-thu-chien', 'Cá thu chiên', 'dish', 'Món chiên', 'phần', 130, 203, 17.5, 0, 14.6, 0, 0, 74, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('khoai-tay-chien', 'Khoai tây chiên', 'dish', 'Món chiên', 'phần', 165, 165.4, 1.8, 18.2, 9.2, 1.3, 0, 5, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('khoai-lang-luoc', 'Khoai lang luộc', 'dish', 'Món luộc', 'củ', 150, 119, 1.1, 27.9, 0.2, 1.3, 0, 11, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('sua-chua-chuoi', 'Sữa chua chuối', 'dish', 'Bữa phụ', 'hộp', 160, 74.5, 3.1, 11.8, 1.7, 1, 0, 29, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('ca-phe-sua-da', 'Cà phê sữa đá', 'dish', 'Đồ uống', 'ly', 175, 47.6, 1.3, 8, 1.2, 0, 0, 18, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('sinh-to-chuoi-sua', 'Sinh tố chuối sữa', 'dish', 'Đồ uống', 'ly', 270, 77, 2.4, 12.6, 2, 1.2, 0, 25, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('com-rang-trung', 'Cơm rang trứng', 'dish', 'Cơm', 'đĩa', 333, 150.3, 4.5, 21.5, 4.7, 0.3, 0, 146, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('com-ga-xoi-mo', 'Cơm gà xối mỡ', 'dish', 'Cơm', 'phần', 413, 155.5, 7.7, 17.3, 5.9, 0.3, 0, 119, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('com-thit-kho-trung', 'Cơm thịt kho trứng', 'dish', 'Cơm', 'phần', 420, 146.5, 7.8, 18.2, 4.3, 0.2, 0, 218, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('com-ca-kho', 'Cơm cá kho', 'dish', 'Cơm', 'phần', 397, 124.8, 6.7, 18.9, 2.2, 0.3, 0, 219, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('com-chien-ca', 'Cơm chiên cá', 'dish', 'Cơm', 'đĩa', 438, 132.1, 6.7, 16.8, 3.9, 0.4, 0, 36, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('com-tam-day-du', 'Cơm tấm sườn bì chả', 'dish', 'Cơm', 'phần', 486, 136.2, 8.5, 14.8, 4.4, 0.2, 0, 192, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('com-rau-luoc-trung', 'Cơm rau luộc trứng', 'dish', 'Cơm', 'phần', 407, 93.9, 4, 15.1, 1.7, 0.9, 0, 321, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('bun-cha-ca', 'Bún chả cá', 'dish', 'Món nước', 'tô', 403, 118.3, 6.7, 17.8, 2.1, 0.1, 0, 182, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('bun-rieu-chay', 'Bún riêu chay', 'dish', 'Món nước', 'tô', 418, 103, 4.1, 18.3, 1.5, 0.2, 0, 161, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('mi-ga', 'Mì gà', 'dish', 'Món nước', 'tô', 529, 83, 4.7, 8.7, 3.3, 0.4, 0, 102, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('hu-tieu-nuoc', 'Hủ tiếu nước', 'dish', 'Món nước', 'tô', 368, 129.3, 8.6, 19.2, 1.7, 0, 0, 211, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('chao-ga', 'Cháo gà', 'dish', 'Món nước', 'bát', 436, 69, 4.5, 7.1, 2.5, 0.1, 0, 194, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('chao-ca-basa', 'Cháo cá', 'dish', 'Món nước', 'bát', 441, 49.5, 4, 7, 0.6, 0.1, 0, 102, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('canh-chua-ca-thu', 'Canh chua cá thu', 'dish', 'Canh', 'bát', 275, 81.3, 8.8, 3.8, 3.4, 0.5, 0, 325, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('canh-cai-ngot-thit', 'Canh cải ngọt thịt', 'dish', 'Canh', 'bát', 217, 51, 6.5, 1.7, 1.9, 0.8, 0, 576, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('canh-ca-rot-khoai-tay', 'Canh cà rốt khoai tây', 'dish', 'Canh', 'bát', 252, 79.6, 5, 11.4, 1.4, 1.5, 0, 351, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('canh-dau-hu-ca-chua', 'Canh đậu hũ cà chua', 'dish', 'Canh', 'bát', 235, 69.4, 4.9, 3.5, 4.2, 0.5, 0, 342, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('rau-muong-luoc', 'Rau muống luộc', 'dish', 'Rau', 'đĩa', 207, 25, 2.7, 3, 0.3, 1.7, 0, 605, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('cai-ngot-xao-toi', 'Cải ngọt xào tỏi', 'dish', 'Rau', 'đĩa', 221, 53.3, 1.9, 3.3, 3.8, 1.2, 0, 205, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('nom-ca-rot-dua-leo', 'Nộm cà rốt dưa leo', 'dish', 'Rau', 'đĩa', 276, 81.6, 2.7, 10.4, 3.4, 1.9, 0, 255, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('dau-hu-sot-ca-chua', 'Đậu hũ sốt cà chua', 'dish', 'Món mặn', 'phần', 294, 82.6, 5, 3.5, 5.6, 0.5, 0, 170, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('thit-heo-kho', 'Thịt heo kho', 'dish', 'Món mặn', 'phần', 183, 162.3, 16.1, 5.4, 8.1, 0, 0, 689, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('ca-basa-kho-to', 'Cá basa kho tộ', 'dish', 'Món mặn', 'phần', 213, 115.1, 14, 4.7, 4.5, 0, 0, 604, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('ca-thu-hap', 'Cá thu hấp', 'dish', 'Món mặn', 'phần', 208, 116.2, 14.3, 2.4, 5.5, 0.5, 0, 371, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('tom-rang-nuoc-mam', 'Tôm rang nước mắm', 'dish', 'Món mặn', 'phần', 176, 124.3, 15.8, 4.7, 4.7, 0.1, 0, 574, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('ga-nuong', 'Gà nướng', 'dish', 'Món mặn', 'phần', 211, 212.7, 17.8, 5, 13.6, 0.1, 0, 432, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('bo-xao-cai-ngot', 'Bò xào cải ngọt', 'dish', 'Món mặn', 'phần', 290, 85.8, 9.8, 1.9, 4.4, 0.7, 0, 203, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('banh-mi-trung', 'Bánh mì trứng', 'dish', 'Bánh mì', 'ổ', 238, 202.4, 9.2, 22.9, 7.6, 0.1, 0, 356, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('banh-mi-ca', 'Bánh mì cá', 'dish', 'Bánh mì', 'ổ', 265, 156, 9.5, 21.2, 3.4, 0.4, 0, 212, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('banh-mi-thit-nuong', 'Bánh mì thịt nướng', 'dish', 'Bánh mì', 'ổ', 272, 161.5, 10.5, 22.2, 3, 0.4, 0, 436, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('xoi-dau-phong', 'Xôi đậu phộng', 'dish', 'Xôi', 'phần', 200, 258.1, 7.5, 39.5, 7.8, 1, 0, 393, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('xoi-ga', 'Xôi gà', 'dish', 'Xôi', 'phần', 264, 219, 9.4, 28.5, 7.6, 0.3, 0, 170, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('khoai-tay-nghien-sua', 'Khoai tây nghiền sữa', 'dish', 'Món phụ', 'phần', 270, 108.3, 2.2, 15.9, 3.8, 1, 0, 303, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('khoai-lang-nuong', 'Khoai lang nướng', 'dish', 'Món phụ', 'củ', 200, 119, 1.1, 27.9, 0.2, 1.3, 0, 11, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('trung-luoc', 'Trứng luộc', 'dish', 'Món phụ', 'phần', 101, 164.4, 12.9, 1, 11.5, 0, 0, 515, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('sua-chua-trai-cay', 'Sữa chua trái cây', 'dish', 'Tráng miệng', 'ly', 220, 72.5, 2.5, 13.1, 1.3, 1.4, 0, 21, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('sinh-to-tao-sua', 'Sinh tố táo sữa', 'dish', 'Đồ uống', 'ly', 300, 56.5, 1.8, 9.3, 1.7, 1.2, 0, 23, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('dau-phong-rang', 'Đậu phộng rang', 'dish', 'Món phụ', 'phần', 51, 561.8, 25.3, 15.7, 43.6, 5.4, 0, 773, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('goi-cuon-tom-thit', 'Gỏi cuốn tôm thịt', 'dish', 'Món cuốn', 'cuốn', 263, 119, 10.6, 9.2, 4.2, 0.7, 0, 293, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('bun-cha', 'Bún chả', 'dish', 'Món khô', 'phần', 425, 128.2, 7.4, 17, 3.1, 0.3, 0, 211, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('tra-sua-tran-chau', 'Trà sữa trân châu', 'dish', 'Đồ uống', 'ly', 360, 91.3, 0.4, 17.1, 2.5, 0, 0, 3, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('tra-sua-khong-tran-chau', 'Trà sữa không trân châu', 'dish', 'Đồ uống', 'ly', 295, 74.2, 0.4, 11.7, 3, 0, 0, 3, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('sua-tuoi-tran-chau-duong-den', 'Sữa tươi trân châu đường đen', 'dish', 'Đồ uống', 'ly', 295, 110.8, 2.2, 20.5, 2.3, 0, 0, 32, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('tra-da', 'Trà đá', 'dish', 'Đồ uống', 'ly', 250, 1, 0, 0.3, 0, 0, 0, 3, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('tra-dao', 'Trà đào', 'dish', 'Đồ uống', 'ly', 320, 37.3, 0.1, 9.6, 0, 0.2, 0, 3, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('tra-chanh', 'Trà chanh', 'dish', 'Đồ uống', 'ly', 275, 37.3, 0, 9.4, 0, 0, 0, 3, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('ca-phe-den-da', 'Cà phê đen đá', 'dish', 'Đồ uống', 'ly', 160, 26.9, 0.2, 6.5, 0, 0, 0, 3, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('bac-xiu', 'Bạc xỉu', 'dish', 'Đồ uống', 'ly', 190, 83.4, 3, 11.2, 3.1, 0, 0, 42, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('sinh-to-bo', 'Sinh tố bơ', 'dish', 'Đồ uống', 'ly', 250, 139.7, 3.2, 12.5, 9.4, 3.2, 0, 35, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('sinh-to-xoai', 'Sinh tố xoài', 'dish', 'Đồ uống', 'ly', 270, 84.7, 2.1, 14.6, 2, 0.3, 0, 25, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('sua-dau-nanh-co-duong', 'Sữa đậu nành', 'dish', 'Đồ uống', 'ly', 265, 49.1, 2.9, 6, 1.5, 0, 0, 0, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('che-dau-xanh', 'Chè đậu xanh', 'dish', 'Tráng miệng', 'ly', 285, 94.9, 3.4, 16.4, 1.8, 0.7, 0, 3, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('che-dau-den', 'Chè đậu đen', 'dish', 'Tráng miệng', 'ly', 280, 92.7, 3.6, 16.7, 1.4, 0.6, 0, 2, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('che-ba-mau', 'Chè ba màu', 'dish', 'Tráng miệng', 'ly', 250, 125, 5, 20.9, 2.5, 0.9, 0, 3, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('banh-flan', 'Bánh flan', 'dish', 'Tráng miệng', 'hũ', 123, 148.9, 6.8, 15.8, 6.4, 0, 0, 78, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('bun-rieu-cua', 'Bún riêu cua', 'dish', 'Món nước', 'tô', 645, 62.8, 2.8, 8.8, 1.8, 0.3, 0, 63, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('mi-quang', 'Mì Quảng', 'dish', 'Món nước', 'tô', 481, 127.9, 6.6, 15.4, 4.2, 0.2, 0, 162, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('banh-canh-cua', 'Bánh canh cua', 'dish', 'Món nước', 'tô', 561, 78.6, 3.5, 11.6, 1.9, 0, 0, 124, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('mien-ga', 'Miến gà', 'dish', 'Món nước', 'tô', 508, 71.5, 3.4, 9.8, 2.1, 0.2, 0, 136, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('chao-thit-bam', 'Cháo thịt bằm', 'dish', 'Món nước', 'bát', 400, 52.5, 3.2, 7.7, 0.9, 0.1, 0, 107, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('mi-tom-trung', 'Mì tôm trứng', 'dish', 'Món nước', 'tô', 430, 97.7, 3.1, 11.2, 4.3, 0, 0, 207, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('pho-bo-vien', 'Phở bò viên', 'dish', 'Món nước', 'tô', 506, 93.9, 5.4, 15.7, 0.9, 0, 0, 165, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('bun-thit-nuong', 'Bún thịt nướng', 'dish', 'Món khô', 'tô', 400, 141.1, 6.9, 16.2, 5.3, 0.5, 0, 316, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('bun-dau-mam-tom', 'Bún đậu mắm tôm', 'dish', 'Món khô', 'mẹt', 480, 119.2, 5.9, 12, 5.3, 0.3, 0, 289, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('pho-cuon', 'Phở cuốn', 'dish', 'Món cuốn', 'phần', 195, 117.9, 7.5, 19.2, 1.1, 0.1, 0, 426, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('mi-xao-bo', 'Mì xào bò', 'dish', 'Món xào', 'đĩa', 382, 130.2, 7.3, 13.8, 5.1, 0.9, 0, 165, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('banh-cuon', 'Bánh cuốn', 'dish', 'Món khô', 'đĩa', 303, 135.3, 6.2, 18.2, 4.1, 0, 0, 471, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('banh-xeo', 'Bánh xèo', 'dish', 'Món chiên', 'cái', 270, 174.3, 6.1, 16.5, 9.4, 0.3, 0, 27, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('nem-ran', 'Chả giò (nem rán)', 'dish', 'Món chiên', 'phần', 140, 276.7, 9.8, 18.5, 18, 0.5, 0, 44, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('banh-bao', 'Bánh bao nhân thịt', 'dish', 'Bánh', 'cái', 156, 235.8, 9.8, 37.8, 4.8, 0, 0, 24, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('banh-chung', 'Bánh chưng', 'dish', 'Bánh', 'miếng', 250, 247, 9.6, 42.3, 4.4, 0.9, 0, 13, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('xoi-xeo', 'Xôi xéo', 'dish', 'Xôi', 'gói', 205, 252.6, 7, 43, 5.9, 0.9, 0, 3, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('com-chien-duong-chau', 'Cơm chiên Dương Châu', 'dish', 'Cơm', 'đĩa', 382, 185.8, 6.2, 19.2, 9, 0.4, 0, 119, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('thit-kho-tau', 'Thịt kho tàu', 'dish', 'Món mặn', 'phần', 250, 187.2, 11.4, 4.3, 13.8, 0.2, 0, 462, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('ga-kho-gung', 'Gà kho gừng', 'dish', 'Món mặn', 'phần', 174, 218.8, 17.8, 3.7, 14.7, 0, 0, 602, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('suon-xao-chua-ngot', 'Sườn xào chua ngọt', 'dish', 'Món mặn', 'phần', 218, 193.2, 12.6, 5.5, 13.4, 0.2, 0, 331, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('suon-nuong', 'Sườn nướng', 'dish', 'Món mặn', 'miếng', 178, 206.3, 15.5, 5.5, 13.6, 0.1, 0, 492, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('bo-luc-lac', 'Bò lúc lắc', 'dish', 'Món mặn', 'phần', 225, 140.4, 14.8, 2.6, 7.9, 0.2, 0, 237, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('muc-xao-hanh-tay', 'Mực xào hành tây', 'dish', 'Món xào', 'đĩa', 226, 100, 11.4, 2.3, 5, 0.2, 0, 239, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('ca-hoi-ap-chao', 'Cá hồi áp chảo', 'dish', 'Món mặn', 'phần', 156, 228.8, 19.6, 0, 16.1, 0, 0, 307, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('ga-luoc', 'Gà luộc', 'dish', 'Món luộc', 'phần', 151, 197.7, 20.2, 0, 13, 0, 0, 328, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('uc-ga-ap-chao', 'Ức gà áp chảo', 'dish', 'Món mặn', 'miếng', 156, 144.2, 21.6, 0, 5.7, 0, 0, 293, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('dau-hu-nhoi-thit', 'Đậu hũ nhồi thịt sốt cà', 'dish', 'Món mặn', 'phần', 296, 108.1, 8, 2.7, 7.3, 0.3, 0, 176, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('vit-quay', 'Vịt quay', 'dish', 'Món mặn', 'phần', 163, 260.6, 16.8, 3.3, 20.1, 0, 0, 328, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('ga-ran', 'Gà rán', 'dish', 'Món chiên', 'miếng', 150, 283.7, 17.3, 7.3, 20.6, 0, 0, 56, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('canh-bi-dao-thit', 'Canh bí đao nấu thịt', 'dish', 'Canh', 'bát', 295, 25.5, 3, 1.3, 0.9, 0.5, 0, 143, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('canh-bi-do-thit', 'Canh bí đỏ thịt bằm', 'dish', 'Canh', 'bát', 295, 31.6, 2.8, 2.9, 0.9, 0.4, 0, 141, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('dau-que-xao-toi', 'Đậu que xào tỏi', 'dish', 'Rau', 'đĩa', 168, 75.3, 1.9, 7.2, 4.9, 2.5, 0, 239, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('bap-cai-luoc', 'Bắp cải luộc', 'dish', 'Rau', 'đĩa', 205, 29.1, 1.9, 5.4, 0.1, 1.6, 0, 209, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('bong-cai-xao-toi', 'Bông cải xanh xào tỏi', 'dish', 'Rau', 'đĩa', 168, 78, 2.8, 6.8, 5.1, 2.4, 0, 264, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('ca-tim-nuong-mo-hanh', 'Cà tím nướng mỡ hành', 'dish', 'Rau', 'đĩa', 228, 60.9, 1.1, 4.3, 4.4, 1.4, 0, 278, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('goi-ga-bap-cai', 'Gỏi gà bắp cải', 'dish', 'Rau', 'đĩa', 258, 116.6, 8.4, 7.6, 5.9, 1.2, 0, 342, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('salad-uc-ga', 'Salad ức gà', 'dish', 'Rau', 'đĩa', 290, 82.7, 8.4, 1.8, 4.4, 0.5, 0, 21, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('banh-mi-pate', 'Bánh mì pa tê', 'dish', 'Bánh mì', 'ổ', 180, 256.2, 9.1, 29.8, 10.8, 0.1, 0, 503, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('hamburger-bo', 'Hamburger bò', 'dish', 'Bánh mì', 'cái', 243, 229.6, 11.5, 21.2, 10.8, 0.1, 0, 311, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('pizza', 'Pizza', 'dish', 'Bánh mì', 'miếng', 125, 234.3, 8.6, 26.4, 10.5, 0.1, 0, 269, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('yen-mach-sua-chuoi', 'Yến mạch sữa chuối', 'dish', 'Bữa phụ', 'bát', 290, 112.4, 4.8, 16.3, 3.3, 1.9, 0, 31, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('bap-luoc', 'Bắp luộc', 'dish', 'Ăn vặt', 'trái', 150, 86, 3.3, 18.7, 1.4, 2, 0, 15, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('khoai-mi-hap', 'Khoai mì hấp', 'dish', 'Ăn vặt', 'khúc', 150, 160, 1.4, 38.1, 0.3, 1.8, 0, 14, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('banh-trang-tron', 'Bánh tráng trộn', 'dish', 'Ăn vặt', 'bịch', 135, 292.5, 6.7, 37.8, 12.6, 0.7, 0, 23, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts'),
  ('trung-vit-lon-luoc', 'Hột vịt lộn luộc', 'dish', 'Ăn vặt', 'quả', 61, 179, 13.4, 3.9, 12.2, 0, 0, 787, 'Tính từ thành phần — xem packages/seed/src/data/ingredients.ts')
on conflict (slug) do update set
    name_vi = excluded.name_vi,
    kind = excluded.kind,
    category = excluded.category,
    serving_name = excluded.serving_name,
    serving_grams = excluded.serving_grams,
    kcal_per_100g = excluded.kcal_per_100g,
    protein_g = excluded.protein_g,
    carb_g = excluded.carb_g,
    fat_g = excluded.fat_g,
    fiber_g = excluded.fiber_g,
    sugar_g = excluded.sugar_g,
    sodium_mg = excluded.sodium_mg,
    source_ref = excluded.source_ref
;

-- 2. Bí danh tên món (biến thể địa phương, cách gọi khác)
with alias_seed (slug, alias) as (
  values
  ('com-trang', 'cơm'),
  ('com-trang', 'com'),
  ('thit-bo-nac', 'bò'),
  ('thit-bo-nac', 'bo'),
  ('thit-heo-nac', 'thịt lợn nạc'),
  ('thit-heo-nac', 'heo nạc'),
  ('thit-ga-ta', 'gà'),
  ('thit-ga-ta', 'ga'),
  ('trung-ga', 'trứng'),
  ('trung-ga', 'trung ga'),
  ('tom-tuoi', 'tôm'),
  ('tom-tuoi', 'tom'),
  ('dau-hu', 'đậu phụ'),
  ('dau-hu', 'tau hu'),
  ('dau-phong', 'lạc'),
  ('dau-phong', 'dau phong rang'),
  ('sua-chua-khong-duong', 'yaourt'),
  ('sua-chua-khong-duong', 'sua chua'),
  ('dua-leo', 'dưa chuột'),
  ('hanh-la', 'hành'),
  ('hanh-la', 'hanh la'),
  ('chuoi-tieu', 'chuối'),
  ('chuoi-tieu', 'chuoi'),
  ('tao-tay', 'táo'),
  ('tao-tay', 'tao'),
  ('duong-trang', 'đường'),
  ('duong-trang', 'duong'),
  ('ca-phe-den', 'cà phê'),
  ('ca-phe-den', 'ca phe'),
  ('ca-phe-den', 'cf'),
  ('bun-tuoi', 'bún'),
  ('bun-tuoi', 'bun'),
  ('gao-nep', 'gạo nếp'),
  ('gao-nep', 'gao nep'),
  ('mien-dong', 'mien dong'),
  ('mien-dong', 'miến khô'),
  ('banh-trang', 'bánh đa nem'),
  ('banh-trang', 'banh da nem'),
  ('banh-trang', 'banh trang'),
  ('mi-trung', 'mì trứng'),
  ('mi-trung', 'mi trung'),
  ('mi-trung', 'mì vàng'),
  ('bot-gao', 'bot gao'),
  ('bot-mi', 'bot mi'),
  ('khoai-mi', 'khoai mì'),
  ('khoai-mi', 'khoai mi'),
  ('khoai-mi', 'sắn'),
  ('khoai-mi', 'san'),
  ('ngo-ngot', 'bắp mỹ'),
  ('ngo-ngot', 'bap my'),
  ('ngo-ngot', 'ngô ngọt'),
  ('ngo-ngot', 'ngo ngot'),
  ('yen-mach', 'yen mach'),
  ('yen-mach', 'oats'),
  ('yen-mach', 'oatmeal'),
  ('nuoc-loc', 'nước suối'),
  ('nuoc-loc', 'nuoc suoi'),
  ('nuoc-loc', 'nuoc loc'),
  ('nuoc-loc', 'nước uống'),
  ('thit-ba-chi', 'ba chỉ'),
  ('thit-ba-chi', 'ba chi'),
  ('thit-ba-chi', 'thịt ba rọi'),
  ('thit-ba-chi', 'ba roi'),
  ('suon-heo', 'sườn'),
  ('suon-heo', 'suon'),
  ('suon-heo', 'sườn non'),
  ('suon-heo', 'suon non'),
  ('cha-lua', 'giò lụa'),
  ('cha-lua', 'gio lua'),
  ('cha-lua', 'cha lua'),
  ('cha-lua', 'giò'),
  ('lap-xuong', 'lạp xường'),
  ('lap-xuong', 'lap xuong'),
  ('xuc-xich', 'xuc xich'),
  ('xuc-xich', 'xúc xích heo'),
  ('thit-vit', 'vịt'),
  ('thit-vit', 'vit'),
  ('thit-vit', 'thit vit'),
  ('pate', 'pate'),
  ('pate', 'pa tê'),
  ('pate', 'pa-tê'),
  ('uc-ga', 'ức gà'),
  ('uc-ga', 'uc ga'),
  ('uc-ga', 'ức gà sống'),
  ('muc', 'mực'),
  ('muc', 'muc'),
  ('cua-dong', 'cua'),
  ('cua-dong', 'cua dong'),
  ('ca-hoi', 'ca hoi'),
  ('ca-hoi', 'salmon'),
  ('mam-tom', 'mam tom'),
  ('trung-vit', 'hột vịt'),
  ('trung-vit', 'hot vit'),
  ('trung-vit', 'trung vit'),
  ('trung-vit-lon', 'hột vịt lộn'),
  ('trung-vit-lon', 'hot vit lon'),
  ('trung-vit-lon', 'trung vit lon'),
  ('trung-vit-lon', 'vịt lộn'),
  ('dau-xanh', 'đậu xanh'),
  ('dau-xanh', 'dau xanh'),
  ('dau-den', 'đậu đen'),
  ('dau-den', 'dau den'),
  ('sua-dau-nanh', 'sua dau nanh khong duong'),
  ('dau-que', 'đậu cô ve'),
  ('dau-que', 'dau co ve'),
  ('dau-que', 'dau que'),
  ('gia-do', 'giá'),
  ('gia-do', 'gia do'),
  ('gia-do', 'giá đậu'),
  ('bi-dao', 'bí xanh'),
  ('bi-dao', 'bi xanh'),
  ('bi-dao', 'bi dao'),
  ('bi-do', 'bí ngô'),
  ('bi-do', 'bi ngo'),
  ('bi-do', 'bi do'),
  ('bap-cai', 'cải bắp'),
  ('bap-cai', 'cai bap'),
  ('bap-cai', 'bap cai'),
  ('xa-lach', 'xa lach'),
  ('xa-lach', 'rau sống'),
  ('xa-lach', 'rau song'),
  ('hanh-tay', 'hanh tay'),
  ('bong-cai-xanh', 'súp lơ xanh'),
  ('bong-cai-xanh', 'sup lo xanh'),
  ('bong-cai-xanh', 'bong cai'),
  ('bong-cai-xanh', 'broccoli'),
  ('ca-tim', 'ca tim'),
  ('xoai-chin', 'xoài'),
  ('xoai-chin', 'xoai'),
  ('dua-hau', 'dua hau'),
  ('cam', 'quả cam'),
  ('cam', 'cam sành'),
  ('cam', 'cam sanh'),
  ('buoi', 'buoi'),
  ('thanh-long', 'thanh long'),
  ('du-du', 'đu đủ'),
  ('du-du', 'du du'),
  ('oi', 'quả ổi'),
  ('oi', 'qua oi'),
  ('nho', 'nho xanh'),
  ('nho', 'nho đỏ'),
  ('bo-qua', 'trái bơ'),
  ('bo-qua', 'trai bo'),
  ('bo-qua', 'quả bơ'),
  ('bo-qua', 'qua bo'),
  ('bo-qua', 'avocado'),
  ('sau-rieng', 'sau rieng'),
  ('nuoc-dua', 'nuoc dua'),
  ('nuoc-dua', 'dừa tươi'),
  ('nuoc-dua', 'dua tuoi'),
  ('nuoc-cam', 'nước cam'),
  ('nuoc-cam', 'nuoc cam'),
  ('nuoc-mia', 'nuoc mia'),
  ('tra-pha', 'trà nóng'),
  ('tra-pha', 'tra nong'),
  ('tra-pha', 'trà xanh không đường'),
  ('tran-chau', 'tran chau'),
  ('tran-chau', 'boba'),
  ('bot-kem-beo', 'bot kem beo'),
  ('bot-kem-beo', 'creamer'),
  ('sua-tuoi-co-duong', 'sua tuoi co duong'),
  ('sua-tuoi-co-duong', 'sữa hộp'),
  ('sua-tuoi-co-duong', 'sua hop'),
  ('nuoc-ngot', 'nước ngọt'),
  ('nuoc-ngot', 'nuoc ngot'),
  ('nuoc-ngot', 'coca'),
  ('nuoc-ngot', 'coca cola'),
  ('nuoc-ngot', 'pepsi'),
  ('kem-vani', 'kem'),
  ('kem-vani', 'kem que'),
  ('kem-vani', 'kem vani'),
  ('kem-vani', 'kem ốc quế'),
  ('dao-ngam', 'dao ngam'),
  ('dao-ngam', 'đào hộp'),
  ('nuoc-cot-dua', 'nuoc cot dua'),
  ('nuoc-tuong', 'xì dầu'),
  ('nuoc-tuong', 'xi dau'),
  ('nuoc-tuong', 'nuoc tuong'),
  ('mayonnaise', 'mayonnaise'),
  ('mayonnaise', 'mayo'),
  ('pho-mai', 'phô mai'),
  ('pho-mai', 'pho mai'),
  ('pho-mai', 'cheese'),
  ('tuong-ca', 'tương cà chua'),
  ('tuong-ca', 'tuong ca'),
  ('tuong-ca', 'ketchup'),
  ('pho-bo', 'pho'),
  ('pho-bo', 'phở'),
  ('pho-bo', 'pho bo tai'),
  ('pho-ga', 'pho ga'),
  ('bun-bo-hue', 'bun bo'),
  ('bun-bo-hue', 'bún bò'),
  ('com-tam-suon', 'com tam'),
  ('com-tam-suon', 'cơm tấm'),
  ('com-tam-suon', 'cơm sườn'),
  ('com-tam-suon', 'com suon'),
  ('com-ga', 'com ga'),
  ('com-trung', 'com trung'),
  ('com-trung', 'cơm rang trứng'),
  ('banh-mi-thit', 'banh mi'),
  ('banh-mi-thit', 'bánh mì'),
  ('goi-cuon', 'goi cuon'),
  ('goi-cuon', 'gỏi cuốn'),
  ('goi-cuon', 'summer roll'),
  ('canh-rau-muong', 'canh rau muong'),
  ('canh-rau-muong', 'canh rau'),
  ('rau-muong-xao-toi', 'rau muong xao toi'),
  ('rau-muong-xao-toi', 'rau xao toi'),
  ('dau-hu-chien', 'dau hu chien'),
  ('dau-hu-chien', 'đậu phụ rán'),
  ('trung-chien', 'trung chien'),
  ('trung-chien', 'trứng rán'),
  ('ca-thu-chien', 'ca thu chien'),
  ('khoai-tay-chien', 'khoai tay chien'),
  ('khoai-tay-chien', 'french fries'),
  ('khoai-lang-luoc', 'khoai lang luoc'),
  ('sua-chua-chuoi', 'sua chua chuoi'),
  ('sua-chua-chuoi', 'yogurt chuối'),
  ('ca-phe-sua-da', 'ca phe sua da'),
  ('ca-phe-sua-da', 'cà phê sữa'),
  ('sinh-to-chuoi-sua', 'sinh to chuoi'),
  ('sinh-to-chuoi-sua', 'sinh tố chuối'),
  ('com-rang-trung', 'com rang'),
  ('com-rang-trung', 'cơm chiên trứng'),
  ('com-ga-xoi-mo', 'com ga xoi mo'),
  ('com-thit-kho-trung', 'com thit kho'),
  ('com-thit-kho-trung', 'cơm thịt kho'),
  ('com-ca-kho', 'com ca kho'),
  ('com-ca-kho', 'cơm cá basa kho'),
  ('com-chien-ca', 'com chien ca'),
  ('com-chien-ca', 'cơm rang cá'),
  ('com-tam-day-du', 'com tam day du'),
  ('com-tam-day-du', 'cơm tấm đầy đủ'),
  ('com-rau-luoc-trung', 'com rau trung'),
  ('com-rau-luoc-trung', 'cơm rau luộc'),
  ('bun-cha-ca', 'bun cha ca'),
  ('bun-cha-ca', 'bún chả cá Nha Trang'),
  ('bun-rieu-chay', 'bun rieu chay'),
  ('mi-ga', 'mi ga'),
  ('mi-ga', 'mì gà trứng'),
  ('hu-tieu-nuoc', 'hu tieu'),
  ('hu-tieu-nuoc', 'hủ tiếu'),
  ('hu-tieu-nuoc', 'hủ tiếu nam vang'),
  ('hu-tieu-nuoc', 'hu tieu nam vang'),
  ('chao-ga', 'chao ga'),
  ('chao-ga', 'cháo gà ta'),
  ('chao-ca-basa', 'chao ca'),
  ('chao-ca-basa', 'cháo cá basa'),
  ('canh-chua-ca-thu', 'canh chua ca'),
  ('canh-chua-ca-thu', 'canh chua cá'),
  ('canh-cai-ngot-thit', 'canh cai ngot'),
  ('canh-cai-ngot-thit', 'canh cải thịt'),
  ('canh-ca-rot-khoai-tay', 'canh ca rot'),
  ('canh-ca-rot-khoai-tay', 'canh khoai tây cà rốt'),
  ('canh-dau-hu-ca-chua', 'canh dau hu'),
  ('canh-dau-hu-ca-chua', 'canh đậu hũ'),
  ('rau-muong-luoc', 'rau muong luoc'),
  ('rau-muong-luoc', 'rau luộc'),
  ('cai-ngot-xao-toi', 'cai ngot xao toi'),
  ('cai-ngot-xao-toi', 'cải xào tỏi'),
  ('nom-ca-rot-dua-leo', 'nom'),
  ('nom-ca-rot-dua-leo', 'nộm rau'),
  ('nom-ca-rot-dua-leo', 'salad dưa leo'),
  ('dau-hu-sot-ca-chua', 'dau hu sot ca'),
  ('dau-hu-sot-ca-chua', 'đậu hũ chiên sốt cà'),
  ('thit-heo-kho', 'thit kho'),
  ('thit-heo-kho', 'thịt kho tàu'),
  ('ca-basa-kho-to', 'ca kho to'),
  ('ca-basa-kho-to', 'cá kho'),
  ('ca-thu-hap', 'ca thu hap'),
  ('ca-thu-hap', 'cá hấp'),
  ('tom-rang-nuoc-mam', 'tom rang'),
  ('tom-rang-nuoc-mam', 'tôm rang'),
  ('ga-nuong', 'ga nuong'),
  ('ga-nuong', 'gà nướng mật ong'),
  ('bo-xao-cai-ngot', 'bo xao'),
  ('bo-xao-cai-ngot', 'bò xào rau'),
  ('banh-mi-trung', 'banh mi trung'),
  ('banh-mi-trung', 'bánh mì ốp la'),
  ('banh-mi-ca', 'banh mi ca'),
  ('banh-mi-ca', 'bánh mì cá hộp'),
  ('banh-mi-thit-nuong', 'banh mi thit'),
  ('banh-mi-thit-nuong', 'bánh mì thịt'),
  ('xoi-dau-phong', 'xoi dau'),
  ('xoi-dau-phong', 'xôi đậu'),
  ('xoi-ga', 'xoi ga'),
  ('xoi-ga', 'xôi gà ta'),
  ('khoai-tay-nghien-sua', 'khoai tay nghien'),
  ('khoai-tay-nghien-sua', 'purée khoai tây'),
  ('khoai-lang-nuong', 'khoai lang nuong'),
  ('khoai-lang-nuong', 'khoai nướng'),
  ('trung-luoc', 'trung luoc'),
  ('trung-luoc', 'trứng gà luộc'),
  ('sua-chua-trai-cay', 'sua chua trai cay'),
  ('sua-chua-trai-cay', 'sữa chua hoa quả'),
  ('sinh-to-tao-sua', 'sinh to tao'),
  ('sinh-to-tao-sua', 'sinh tố táo'),
  ('dau-phong-rang', 'dau phong'),
  ('dau-phong-rang', 'đậu phộng'),
  ('goi-cuon-tom-thit', 'goi cuon tom'),
  ('goi-cuon-tom-thit', 'gỏi cuốn tôm'),
  ('bun-cha', 'bun cha'),
  ('bun-cha', 'bún chả Hà Nội'),
  ('bun-cha', 'bun cha ha noi'),
  ('tra-sua-tran-chau', 'tra sua'),
  ('tra-sua-tran-chau', 'trà sữa'),
  ('tra-sua-tran-chau', 'tra sua tran chau'),
  ('tra-sua-tran-chau', 'milk tea'),
  ('tra-sua-tran-chau', 'trà sữa size M'),
  ('tra-sua-khong-tran-chau', 'tra sua khong tran chau'),
  ('tra-sua-khong-tran-chau', 'trà sữa không topping'),
  ('tra-sua-khong-tran-chau', 'tra sua khong topping'),
  ('sua-tuoi-tran-chau-duong-den', 'sua tuoi tran chau duong den'),
  ('sua-tuoi-tran-chau-duong-den', 'sữa tươi trân châu'),
  ('sua-tuoi-tran-chau-duong-den', 'tran chau duong den'),
  ('sua-tuoi-tran-chau-duong-den', 'trân châu đường đen'),
  ('tra-da', 'tra da'),
  ('tra-da', 'trà đá vỉa hè'),
  ('tra-dao', 'tra dao'),
  ('tra-dao', 'trà đào cam sả'),
  ('tra-dao', 'tra dao cam sa'),
  ('tra-chanh', 'tra chanh'),
  ('ca-phe-den-da', 'ca phe den'),
  ('ca-phe-den-da', 'cà phê đen'),
  ('ca-phe-den-da', 'cafe den'),
  ('ca-phe-den-da', 'cf den'),
  ('ca-phe-den-da', 'cà phê đen có đường'),
  ('bac-xiu', 'bac xiu'),
  ('bac-xiu', 'bạc sỉu'),
  ('sinh-to-bo', 'sinh to bo'),
  ('sinh-to-bo', 'bơ xay'),
  ('sinh-to-bo', 'bo xay'),
  ('sinh-to-xoai', 'sinh to xoai'),
  ('sua-dau-nanh-co-duong', 'sua dau nanh'),
  ('sua-dau-nanh-co-duong', 'sữa đậu nành có đường'),
  ('sua-dau-nanh-co-duong', 'sữa đậu'),
  ('che-dau-xanh', 'che dau xanh'),
  ('che-dau-den', 'che dau den'),
  ('che-ba-mau', 'che ba mau'),
  ('che-ba-mau', 'chè'),
  ('banh-flan', 'banh flan'),
  ('banh-flan', 'caramen'),
  ('banh-flan', 'bánh caramen'),
  ('bun-rieu-cua', 'bun rieu'),
  ('bun-rieu-cua', 'bún riêu'),
  ('bun-rieu-cua', 'bun rieu cua'),
  ('mi-quang', 'mi quang'),
  ('banh-canh-cua', 'banh canh'),
  ('banh-canh-cua', 'bánh canh'),
  ('banh-canh-cua', 'banh canh cua'),
  ('mien-ga', 'mien ga'),
  ('mien-ga', 'miến'),
  ('mien-ga', 'mien'),
  ('chao-thit-bam', 'chao thit bam'),
  ('chao-thit-bam', 'cháo thịt'),
  ('chao-thit-bam', 'chao thit'),
  ('chao-thit-bam', 'cháo'),
  ('chao-thit-bam', 'chao'),
  ('mi-tom-trung', 'mi tom'),
  ('mi-tom-trung', 'mì tôm'),
  ('mi-tom-trung', 'mì gói'),
  ('mi-tom-trung', 'mi goi'),
  ('mi-tom-trung', 'mì tôm trứng'),
  ('mi-tom-trung', 'mi tom trung'),
  ('pho-bo-vien', 'pho bo vien'),
  ('pho-bo-vien', 'phở tái bò viên'),
  ('bun-thit-nuong', 'bun thit nuong'),
  ('bun-thit-nuong', 'bún thịt nướng chả giò'),
  ('bun-dau-mam-tom', 'bun dau'),
  ('bun-dau-mam-tom', 'bún đậu'),
  ('bun-dau-mam-tom', 'bun dau mam tom'),
  ('pho-cuon', 'pho cuon'),
  ('mi-xao-bo', 'mi xao bo'),
  ('mi-xao-bo', 'mì xào'),
  ('banh-cuon', 'banh cuon'),
  ('banh-cuon', 'bánh cuốn chả'),
  ('banh-xeo', 'banh xeo'),
  ('nem-ran', 'cha gio'),
  ('nem-ran', 'chả giò'),
  ('nem-ran', 'nem ran'),
  ('nem-ran', 'nem rán'),
  ('banh-bao', 'banh bao'),
  ('banh-bao', 'bánh bao'),
  ('banh-chung', 'banh chung'),
  ('banh-chung', 'bánh tét'),
  ('banh-chung', 'banh tet'),
  ('xoi-xeo', 'xoi xeo'),
  ('xoi-xeo', 'xôi'),
  ('xoi-xeo', 'xoi'),
  ('com-chien-duong-chau', 'com chien duong chau'),
  ('com-chien-duong-chau', 'cơm chiên'),
  ('com-chien-duong-chau', 'com chien'),
  ('com-chien-duong-chau', 'cơm rang dương châu'),
  ('thit-kho-tau', 'thit kho tau'),
  ('thit-kho-tau', 'thịt kho hột vịt'),
  ('thit-kho-tau', 'thit kho hot vit'),
  ('ga-kho-gung', 'ga kho gung'),
  ('ga-kho-gung', 'gà kho'),
  ('suon-xao-chua-ngot', 'suon xao chua ngot'),
  ('suon-xao-chua-ngot', 'sườn chua ngọt'),
  ('suon-nuong', 'suon nuong'),
  ('suon-nuong', 'sườn cốt lết nướng'),
  ('bo-luc-lac', 'bo luc lac'),
  ('muc-xao-hanh-tay', 'muc xao'),
  ('muc-xao-hanh-tay', 'mực xào'),
  ('ca-hoi-ap-chao', 'ca hoi ap chao'),
  ('ca-hoi-ap-chao', 'cá hồi nướng'),
  ('ca-hoi-ap-chao', 'ca hoi nuong'),
  ('ga-luoc', 'ga luoc'),
  ('uc-ga-ap-chao', 'uc ga ap chao'),
  ('uc-ga-ap-chao', 'ức gà nướng'),
  ('uc-ga-ap-chao', 'uc ga nuong'),
  ('uc-ga-ap-chao', 'ức gà luộc'),
  ('uc-ga-ap-chao', 'uc ga luoc'),
  ('dau-hu-nhoi-thit', 'dau hu nhoi thit'),
  ('dau-hu-nhoi-thit', 'đậu phụ nhồi thịt'),
  ('vit-quay', 'vit quay'),
  ('ga-ran', 'ga ran'),
  ('ga-ran', 'gà chiên'),
  ('ga-ran', 'ga chien'),
  ('ga-ran', 'gà rán kfc'),
  ('ga-ran', 'kfc'),
  ('canh-bi-dao-thit', 'canh bi dao'),
  ('canh-bi-dao-thit', 'canh bí'),
  ('canh-bi-do-thit', 'canh bi do'),
  ('canh-bi-do-thit', 'canh bí ngô'),
  ('dau-que-xao-toi', 'dau que xao'),
  ('dau-que-xao-toi', 'đậu cô ve xào'),
  ('bap-cai-luoc', 'bap cai luoc'),
  ('bap-cai-luoc', 'cải bắp luộc'),
  ('bong-cai-xao-toi', 'bong cai xao'),
  ('bong-cai-xao-toi', 'súp lơ xào'),
  ('ca-tim-nuong-mo-hanh', 'ca tim nuong'),
  ('ca-tim-nuong-mo-hanh', 'cà tím nướng'),
  ('goi-ga-bap-cai', 'goi ga'),
  ('goi-ga-bap-cai', 'gỏi gà'),
  ('salad-uc-ga', 'salad uc ga'),
  ('salad-uc-ga', 'salad gà'),
  ('banh-mi-pate', 'banh mi pate'),
  ('banh-mi-pate', 'bánh mì pate'),
  ('banh-mi-pate', 'bánh mì thập cẩm'),
  ('banh-mi-pate', 'banh mi thap cam'),
  ('hamburger-bo', 'hamburger'),
  ('hamburger-bo', 'burger'),
  ('hamburger-bo', 'hăm bơ gơ'),
  ('pizza', 'pizza xuc xich'),
  ('pizza', 'pizza hải sản'),
  ('pizza', 'pizza hai san'),
  ('yen-mach-sua-chuoi', 'yen mach sua'),
  ('yen-mach-sua-chuoi', 'cháo yến mạch'),
  ('yen-mach-sua-chuoi', 'oatmeal chuối'),
  ('bap-luoc', 'bap luoc'),
  ('bap-luoc', 'ngô luộc'),
  ('bap-luoc', 'ngo luoc'),
  ('bap-luoc', 'bắp nướng'),
  ('bap-luoc', 'bap nuong'),
  ('khoai-mi-hap', 'khoai mi hap'),
  ('khoai-mi-hap', 'sắn luộc'),
  ('khoai-mi-hap', 'san luoc'),
  ('khoai-mi-hap', 'khoai mì luộc'),
  ('banh-trang-tron', 'banh trang tron'),
  ('trung-vit-lon-luoc', 'trứng vịt lộn luộc'),
  ('trung-vit-lon-luoc', 'hot vit lon luoc')
)
insert into public.food_aliases (food_id, alias)
select f.id, s.alias
from alias_seed s
join public.foods f on f.slug = s.slug
on conflict (food_id, alias) do nothing;

-- 3. Thành phần của món
with component_seed (dish_slug, ingredient_slug, grams) as (
  values
  ('pho-bo', 'pho-tuoi', 250),
  ('pho-bo', 'thit-bo-nac', 80),
  ('pho-bo', 'hanh-la', 15),
  ('pho-bo', 'nuoc-mam', 5),
  ('pho-bo', 'dau-an', 3),
  ('pho-ga', 'pho-tuoi', 250),
  ('pho-ga', 'thit-ga-ta', 90),
  ('pho-ga', 'hanh-la', 15),
  ('pho-ga', 'nuoc-mam', 5),
  ('bun-bo-hue', 'pho-tuoi', 220),
  ('bun-bo-hue', 'thit-bo-nac', 90),
  ('bun-bo-hue', 'hanh-la', 10),
  ('bun-bo-hue', 'nuoc-mam', 8),
  ('bun-bo-hue', 'dau-an', 4),
  ('com-tam-suon', 'com-trang', 250),
  ('com-tam-suon', 'thit-heo-nac', 120),
  ('com-tam-suon', 'dua-leo', 30),
  ('com-tam-suon', 'dau-an', 5),
  ('com-tam-suon', 'nuoc-mam', 8),
  ('com-ga', 'com-trang', 250),
  ('com-ga', 'thit-ga-ta', 120),
  ('com-ga', 'dau-an', 4),
  ('com-ga', 'nuoc-mam', 6),
  ('com-trung', 'com-trang', 200),
  ('com-trung', 'trung-ga', 60),
  ('com-trung', 'dau-an', 5),
  ('com-trung', 'nuoc-mam', 4),
  ('banh-mi-thit', 'banh-mi', 100),
  ('banh-mi-thit', 'thit-heo-nac', 60),
  ('banh-mi-thit', 'dua-leo', 25),
  ('banh-mi-thit', 'dau-an', 3),
  ('goi-cuon', 'pho-tuoi', 60),
  ('goi-cuon', 'tom-tuoi', 40),
  ('goi-cuon', 'rau-muong', 40),
  ('goi-cuon', 'thit-heo-nac', 30),
  ('canh-rau-muong', 'rau-muong', 150),
  ('canh-rau-muong', 'tom-tuoi', 30),
  ('canh-rau-muong', 'nuoc-mam', 5),
  ('canh-rau-muong', 'dau-an', 2),
  ('rau-muong-xao-toi', 'rau-muong', 150),
  ('rau-muong-xao-toi', 'toi', 6),
  ('rau-muong-xao-toi', 'dau-an', 8),
  ('dau-hu-chien', 'dau-hu', 150),
  ('dau-hu-chien', 'dau-an', 10),
  ('trung-chien', 'trung-ga', 100),
  ('trung-chien', 'dau-an', 8),
  ('ca-thu-chien', 'ca-thu', 120),
  ('ca-thu-chien', 'dau-an', 10),
  ('khoai-tay-chien', 'khoai-tay', 150),
  ('khoai-tay-chien', 'dau-an', 15),
  ('khoai-lang-luoc', 'khoai-lang', 150),
  ('sua-chua-chuoi', 'sua-chua-khong-duong', 100),
  ('sua-chua-chuoi', 'chuoi-tieu', 60),
  ('ca-phe-sua-da', 'ca-phe-den', 150),
  ('ca-phe-sua-da', 'sua-dac', 25),
  ('sinh-to-chuoi-sua', 'chuoi-tieu', 120),
  ('sinh-to-chuoi-sua', 'sua-tuoi-khong-duong', 150),
  ('com-rang-trung', 'com-trang', 250),
  ('com-rang-trung', 'trung-ga', 60),
  ('com-rang-trung', 'hanh-la', 10),
  ('com-rang-trung', 'dau-an', 8),
  ('com-rang-trung', 'nuoc-mam', 5),
  ('com-ga-xoi-mo', 'com-trang', 250),
  ('com-ga-xoi-mo', 'thit-ga-ta', 120),
  ('com-ga-xoi-mo', 'dua-leo', 30),
  ('com-ga-xoi-mo', 'dau-an', 8),
  ('com-ga-xoi-mo', 'nuoc-mam', 5),
  ('com-thit-kho-trung', 'com-trang', 250),
  ('com-thit-kho-trung', 'thit-heo-nac', 100),
  ('com-thit-kho-trung', 'trung-ga', 50),
  ('com-thit-kho-trung', 'nuoc-mam', 10),
  ('com-thit-kho-trung', 'duong-trang', 5),
  ('com-thit-kho-trung', 'dau-an', 5),
  ('com-ca-kho', 'com-trang', 250),
  ('com-ca-kho', 'ca-basa', 120),
  ('com-ca-kho', 'nuoc-mam', 10),
  ('com-ca-kho', 'duong-trang', 4),
  ('com-ca-kho', 'dau-an', 5),
  ('com-ca-kho', 'hanh-la', 8),
  ('com-chien-ca', 'com-trang', 250),
  ('com-chien-ca', 'ca-basa', 100),
  ('com-chien-ca', 'trung-ga', 50),
  ('com-chien-ca', 'ca-rot', 30),
  ('com-chien-ca', 'dau-an', 8),
  ('com-tam-day-du', 'com-trang', 250),
  ('com-tam-day-du', 'thit-heo-nac', 150),
  ('com-tam-day-du', 'trung-ga', 40),
  ('com-tam-day-du', 'dua-leo', 30),
  ('com-tam-day-du', 'nuoc-mam', 10),
  ('com-tam-day-du', 'dau-an', 6),
  ('com-rau-luoc-trung', 'com-trang', 200),
  ('com-rau-luoc-trung', 'rau-muong', 150),
  ('com-rau-luoc-trung', 'trung-ga', 50),
  ('com-rau-luoc-trung', 'muoi-an', 2),
  ('com-rau-luoc-trung', 'nuoc-mam', 5),
  ('bun-cha-ca', 'pho-tuoi', 220),
  ('bun-cha-ca', 'ca-basa', 120),
  ('bun-cha-ca', 'ca-chua', 40),
  ('bun-cha-ca', 'hanh-la', 10),
  ('bun-cha-ca', 'nuoc-mam', 8),
  ('bun-cha-ca', 'dau-an', 5),
  ('bun-rieu-chay', 'pho-tuoi', 220),
  ('bun-rieu-chay', 'dau-hu', 100),
  ('bun-rieu-chay', 'ca-chua', 80),
  ('bun-rieu-chay', 'hanh-la', 10),
  ('bun-rieu-chay', 'nuoc-mam', 8),
  ('mi-ga', 'mi-trung', 180),
  ('mi-ga', 'thit-ga-ta', 80),
  ('mi-ga', 'nuoc-loc', 250),
  ('mi-ga', 'hanh-la', 10),
  ('mi-ga', 'nuoc-mam', 6),
  ('mi-ga', 'dau-an', 3),
  ('hu-tieu-nuoc', 'pho-tuoi', 220),
  ('hu-tieu-nuoc', 'thit-heo-nac', 80),
  ('hu-tieu-nuoc', 'tom-tuoi', 50),
  ('hu-tieu-nuoc', 'hanh-la', 10),
  ('hu-tieu-nuoc', 'nuoc-mam', 8),
  ('chao-ga', 'gao-te', 40),
  ('chao-ga', 'nuoc-loc', 300),
  ('chao-ga', 'thit-ga-ta', 80),
  ('chao-ga', 'hanh-la', 10),
  ('chao-ga', 'nuoc-mam', 5),
  ('chao-ga', 'muoi-an', 1),
  ('chao-ca-basa', 'gao-te', 40),
  ('chao-ca-basa', 'nuoc-loc', 300),
  ('chao-ca-basa', 'ca-basa', 90),
  ('chao-ca-basa', 'hanh-la', 10),
  ('chao-ca-basa', 'muoi-an', 1),
  ('canh-chua-ca-thu', 'ca-thu', 120),
  ('canh-chua-ca-thu', 'ca-chua', 80),
  ('canh-chua-ca-thu', 'dua-leo', 50),
  ('canh-chua-ca-thu', 'hanh-la', 10),
  ('canh-chua-ca-thu', 'nuoc-mam', 10),
  ('canh-chua-ca-thu', 'duong-trang', 5),
  ('canh-cai-ngot-thit', 'cai-ngot', 150),
  ('canh-cai-ngot-thit', 'thit-heo-nac', 60),
  ('canh-cai-ngot-thit', 'muoi-an', 2),
  ('canh-cai-ngot-thit', 'nuoc-mam', 5),
  ('canh-ca-rot-khoai-tay', 'ca-rot', 100),
  ('canh-ca-rot-khoai-tay', 'khoai-tay', 100),
  ('canh-ca-rot-khoai-tay', 'thit-heo-nac', 50),
  ('canh-ca-rot-khoai-tay', 'muoi-an', 2),
  ('canh-dau-hu-ca-chua', 'dau-hu', 120),
  ('canh-dau-hu-ca-chua', 'ca-chua', 100),
  ('canh-dau-hu-ca-chua', 'hanh-la', 10),
  ('canh-dau-hu-ca-chua', 'muoi-an', 2),
  ('canh-dau-hu-ca-chua', 'dau-an', 3),
  ('rau-muong-luoc', 'rau-muong', 200),
  ('rau-muong-luoc', 'muoi-an', 2),
  ('rau-muong-luoc', 'nuoc-mam', 5),
  ('cai-ngot-xao-toi', 'cai-ngot', 200),
  ('cai-ngot-xao-toi', 'toi', 8),
  ('cai-ngot-xao-toi', 'dau-an', 8),
  ('cai-ngot-xao-toi', 'nuoc-mam', 5),
  ('nom-ca-rot-dua-leo', 'ca-rot', 100),
  ('nom-ca-rot-dua-leo', 'dua-leo', 100),
  ('nom-ca-rot-dua-leo', 'dau-phong', 20),
  ('nom-ca-rot-dua-leo', 'duong-trang', 8),
  ('nom-ca-rot-dua-leo', 'nuoc-mam', 8),
  ('nom-ca-rot-dua-leo', 'tao-tay', 40),
  ('dau-hu-sot-ca-chua', 'dau-hu', 150),
  ('dau-hu-sot-ca-chua', 'ca-chua', 120),
  ('dau-hu-sot-ca-chua', 'hanh-la', 10),
  ('dau-hu-sot-ca-chua', 'dau-an', 8),
  ('dau-hu-sot-ca-chua', 'nuoc-mam', 6),
  ('thit-heo-kho', 'thit-heo-nac', 150),
  ('thit-heo-kho', 'nuoc-mam', 15),
  ('thit-heo-kho', 'duong-trang', 8),
  ('thit-heo-kho', 'toi', 5),
  ('thit-heo-kho', 'dau-an', 5),
  ('ca-basa-kho-to', 'ca-basa', 180),
  ('ca-basa-kho-to', 'nuoc-mam', 15),
  ('ca-basa-kho-to', 'duong-trang', 8),
  ('ca-basa-kho-to', 'toi', 5),
  ('ca-basa-kho-to', 'dau-an', 5),
  ('ca-thu-hap', 'ca-thu', 150),
  ('ca-thu-hap', 'hanh-la', 15),
  ('ca-thu-hap', 'toi', 5),
  ('ca-thu-hap', 'nuoc-mam', 8),
  ('ca-thu-hap', 'ca-rot', 30),
  ('tom-rang-nuoc-mam', 'tom-tuoi', 150),
  ('tom-rang-nuoc-mam', 'nuoc-mam', 10),
  ('tom-rang-nuoc-mam', 'duong-trang', 5),
  ('tom-rang-nuoc-mam', 'toi', 5),
  ('tom-rang-nuoc-mam', 'dau-an', 6),
  ('ga-nuong', 'thit-ga-ta', 180),
  ('ga-nuong', 'duong-trang', 8),
  ('ga-nuong', 'nuoc-mam', 10),
  ('ga-nuong', 'toi', 8),
  ('ga-nuong', 'dau-an', 5),
  ('bo-xao-cai-ngot', 'thit-bo-nac', 120),
  ('bo-xao-cai-ngot', 'cai-ngot', 150),
  ('bo-xao-cai-ngot', 'toi', 6),
  ('bo-xao-cai-ngot', 'dau-an', 8),
  ('bo-xao-cai-ngot', 'nuoc-mam', 6),
  ('banh-mi-trung', 'banh-mi', 100),
  ('banh-mi-trung', 'trung-ga', 100),
  ('banh-mi-trung', 'dua-leo', 30),
  ('banh-mi-trung', 'dau-an', 5),
  ('banh-mi-trung', 'nuoc-mam', 3),
  ('banh-mi-ca', 'banh-mi', 100),
  ('banh-mi-ca', 'ca-basa', 100),
  ('banh-mi-ca', 'ca-rot', 30),
  ('banh-mi-ca', 'dua-leo', 30),
  ('banh-mi-ca', 'dau-an', 5),
  ('banh-mi-thit-nuong', 'banh-mi', 100),
  ('banh-mi-thit-nuong', 'thit-heo-nac', 100),
  ('banh-mi-thit-nuong', 'ca-rot', 30),
  ('banh-mi-thit-nuong', 'dua-leo', 30),
  ('banh-mi-thit-nuong', 'nuoc-mam', 8),
  ('banh-mi-thit-nuong', 'duong-trang', 4),
  ('xoi-dau-phong', 'gao-nep', 100),
  ('xoi-dau-phong', 'nuoc-loc', 70),
  ('xoi-dau-phong', 'dau-phong', 25),
  ('xoi-dau-phong', 'muoi-an', 2),
  ('xoi-dau-phong', 'dau-an', 3),
  ('xoi-ga', 'gao-nep', 100),
  ('xoi-ga', 'nuoc-loc', 70),
  ('xoi-ga', 'thit-ga-ta', 80),
  ('xoi-ga', 'dau-an', 8),
  ('xoi-ga', 'hanh-la', 5),
  ('xoi-ga', 'muoi-an', 1),
  ('khoai-tay-nghien-sua', 'khoai-tay', 200),
  ('khoai-tay-nghien-sua', 'sua-tuoi-khong-duong', 60),
  ('khoai-tay-nghien-sua', 'dau-an', 8),
  ('khoai-tay-nghien-sua', 'muoi-an', 2),
  ('khoai-lang-nuong', 'khoai-lang', 200),
  ('trung-luoc', 'trung-ga', 100),
  ('trung-luoc', 'muoi-an', 1),
  ('sua-chua-trai-cay', 'sua-chua-khong-duong', 100),
  ('sua-chua-trai-cay', 'chuoi-tieu', 80),
  ('sua-chua-trai-cay', 'tao-tay', 40),
  ('sinh-to-tao-sua', 'tao-tay', 150),
  ('sinh-to-tao-sua', 'sua-tuoi-khong-duong', 150),
  ('dau-phong-rang', 'dau-phong', 50),
  ('dau-phong-rang', 'muoi-an', 1),
  ('goi-cuon-tom-thit', 'pho-tuoi', 60),
  ('goi-cuon-tom-thit', 'tom-tuoi', 60),
  ('goi-cuon-tom-thit', 'thit-heo-nac', 50),
  ('goi-cuon-tom-thit', 'rau-muong', 40),
  ('goi-cuon-tom-thit', 'dua-leo', 30),
  ('goi-cuon-tom-thit', 'nuoc-mam', 8),
  ('goi-cuon-tom-thit', 'dau-phong', 15),
  ('bun-cha', 'pho-tuoi', 200),
  ('bun-cha', 'thit-heo-nac', 120),
  ('bun-cha', 'rau-muong', 50),
  ('bun-cha', 'dua-leo', 30),
  ('bun-cha', 'nuoc-mam', 10),
  ('bun-cha', 'duong-trang', 5),
  ('bun-cha', 'toi', 5),
  ('bun-cha', 'dau-an', 5),
  ('tra-sua-tran-chau', 'tra-pha', 250),
  ('tra-sua-tran-chau', 'bot-kem-beo', 25),
  ('tra-sua-tran-chau', 'duong-trang', 25),
  ('tra-sua-tran-chau', 'tran-chau', 60),
  ('tra-sua-khong-tran-chau', 'tra-pha', 250),
  ('tra-sua-khong-tran-chau', 'bot-kem-beo', 25),
  ('tra-sua-khong-tran-chau', 'duong-trang', 20),
  ('sua-tuoi-tran-chau-duong-den', 'sua-tuoi-khong-duong', 200),
  ('sua-tuoi-tran-chau-duong-den', 'tran-chau', 70),
  ('sua-tuoi-tran-chau-duong-den', 'duong-trang', 25),
  ('tra-da', 'tra-pha', 250),
  ('tra-dao', 'tra-pha', 250),
  ('tra-dao', 'duong-trang', 20),
  ('tra-dao', 'dao-ngam', 50),
  ('tra-chanh', 'tra-pha', 250),
  ('tra-chanh', 'duong-trang', 25),
  ('ca-phe-den-da', 'ca-phe-den', 150),
  ('ca-phe-den-da', 'duong-trang', 10),
  ('bac-xiu', 'ca-phe-den', 60),
  ('bac-xiu', 'sua-dac', 30),
  ('bac-xiu', 'sua-tuoi-khong-duong', 100),
  ('sinh-to-bo', 'bo-qua', 120),
  ('sinh-to-bo', 'sua-dac', 30),
  ('sinh-to-bo', 'sua-tuoi-khong-duong', 100),
  ('sinh-to-xoai', 'xoai-chin', 150),
  ('sinh-to-xoai', 'sua-dac', 20),
  ('sinh-to-xoai', 'sua-tuoi-khong-duong', 100),
  ('sua-dau-nanh-co-duong', 'sua-dau-nanh', 250),
  ('sua-dau-nanh-co-duong', 'duong-trang', 15),
  ('che-dau-xanh', 'dau-xanh', 40),
  ('che-dau-xanh', 'duong-trang', 25),
  ('che-dau-xanh', 'nuoc-loc', 200),
  ('che-dau-xanh', 'nuoc-cot-dua', 20),
  ('che-dau-den', 'dau-den', 40),
  ('che-dau-den', 'duong-trang', 25),
  ('che-dau-den', 'nuoc-loc', 200),
  ('che-dau-den', 'nuoc-cot-dua', 15),
  ('che-ba-mau', 'dau-xanh', 25),
  ('che-ba-mau', 'dau-den', 25),
  ('che-ba-mau', 'duong-trang', 25),
  ('che-ba-mau', 'nuoc-cot-dua', 25),
  ('che-ba-mau', 'nuoc-loc', 150),
  ('banh-flan', 'trung-ga', 40),
  ('banh-flan', 'sua-tuoi-khong-duong', 60),
  ('banh-flan', 'sua-dac', 15),
  ('banh-flan', 'duong-trang', 8),
  ('bun-rieu-cua', 'bun-tuoi', 200),
  ('bun-rieu-cua', 'cua-dong', 60),
  ('bun-rieu-cua', 'trung-ga', 20),
  ('bun-rieu-cua', 'ca-chua', 60),
  ('bun-rieu-cua', 'dau-hu', 40),
  ('bun-rieu-cua', 'nuoc-loc', 250),
  ('bun-rieu-cua', 'mam-tom', 5),
  ('bun-rieu-cua', 'hanh-la', 5),
  ('bun-rieu-cua', 'dau-an', 5),
  ('mi-quang', 'pho-tuoi', 200),
  ('mi-quang', 'thit-heo-nac', 60),
  ('mi-quang', 'tom-tuoi', 40),
  ('mi-quang', 'trung-ga', 25),
  ('mi-quang', 'dau-phong', 10),
  ('mi-quang', 'banh-trang', 10),
  ('mi-quang', 'xa-lach', 20),
  ('mi-quang', 'nuoc-loc', 100),
  ('mi-quang', 'nuoc-mam', 8),
  ('mi-quang', 'dau-an', 8),
  ('banh-canh-cua', 'pho-tuoi', 200),
  ('banh-canh-cua', 'cua-dong', 60),
  ('banh-canh-cua', 'tom-tuoi', 30),
  ('banh-canh-cua', 'nuoc-loc', 250),
  ('banh-canh-cua', 'hanh-la', 5),
  ('banh-canh-cua', 'nuoc-mam', 8),
  ('banh-canh-cua', 'dau-an', 8),
  ('mien-ga', 'mien-dong', 60),
  ('mien-ga', 'thit-ga-ta', 80),
  ('mien-ga', 'nuoc-loc', 350),
  ('mien-ga', 'hanh-la', 10),
  ('mien-ga', 'nuoc-mam', 8),
  ('chao-thit-bam', 'gao-te', 40),
  ('chao-thit-bam', 'nuoc-loc', 300),
  ('chao-thit-bam', 'thit-heo-nac', 50),
  ('chao-thit-bam', 'hanh-la', 5),
  ('chao-thit-bam', 'nuoc-mam', 5),
  ('mi-tom-trung', 'mi-an-lien', 75),
  ('mi-tom-trung', 'trung-ga', 50),
  ('mi-tom-trung', 'nuoc-loc', 300),
  ('mi-tom-trung', 'hanh-la', 5),
  ('pho-bo-vien', 'pho-tuoi', 250),
  ('pho-bo-vien', 'thit-bo-nac', 50),
  ('pho-bo-vien', 'cha-lua', 40),
  ('pho-bo-vien', 'nuoc-loc', 150),
  ('pho-bo-vien', 'hanh-la', 10),
  ('pho-bo-vien', 'nuoc-mam', 6),
  ('bun-thit-nuong', 'bun-tuoi', 200),
  ('bun-thit-nuong', 'thit-heo-nac', 80),
  ('bun-thit-nuong', 'thit-ba-chi', 30),
  ('bun-thit-nuong', 'xa-lach', 30),
  ('bun-thit-nuong', 'dua-leo', 20),
  ('bun-thit-nuong', 'dau-phong', 10),
  ('bun-thit-nuong', 'nuoc-mam', 15),
  ('bun-thit-nuong', 'duong-trang', 10),
  ('bun-thit-nuong', 'dau-an', 5),
  ('bun-dau-mam-tom', 'bun-tuoi', 200),
  ('bun-dau-mam-tom', 'dau-hu', 150),
  ('bun-dau-mam-tom', 'dau-an', 15),
  ('bun-dau-mam-tom', 'cha-lua', 40),
  ('bun-dau-mam-tom', 'dua-leo', 30),
  ('bun-dau-mam-tom', 'xa-lach', 30),
  ('bun-dau-mam-tom', 'mam-tom', 15),
  ('pho-cuon', 'pho-tuoi', 100),
  ('pho-cuon', 'thit-bo-nac', 50),
  ('pho-cuon', 'xa-lach', 30),
  ('pho-cuon', 'nuoc-mam', 10),
  ('pho-cuon', 'duong-trang', 5),
  ('mi-xao-bo', 'mi-trung', 200),
  ('mi-xao-bo', 'thit-bo-nac', 80),
  ('mi-xao-bo', 'cai-ngot', 80),
  ('mi-xao-bo', 'dau-an', 12),
  ('mi-xao-bo', 'nuoc-tuong', 10),
  ('banh-cuon', 'bot-gao', 60),
  ('banh-cuon', 'nuoc-loc', 140),
  ('banh-cuon', 'thit-heo-nac', 40),
  ('banh-cuon', 'cha-lua', 30),
  ('banh-cuon', 'dau-an', 8),
  ('banh-cuon', 'hanh-la', 5),
  ('banh-cuon', 'nuoc-mam', 15),
  ('banh-cuon', 'duong-trang', 5),
  ('banh-xeo', 'bot-gao', 50),
  ('banh-xeo', 'nuoc-loc', 60),
  ('banh-xeo', 'tom-tuoi', 30),
  ('banh-xeo', 'thit-ba-chi', 30),
  ('banh-xeo', 'gia-do', 40),
  ('banh-xeo', 'nuoc-cot-dua', 15),
  ('banh-xeo', 'dau-an', 15),
  ('banh-xeo', 'xa-lach', 30),
  ('nem-ran', 'banh-trang', 20),
  ('nem-ran', 'thit-heo-nac', 60),
  ('nem-ran', 'mien-dong', 10),
  ('nem-ran', 'ca-rot', 20),
  ('nem-ran', 'trung-ga', 10),
  ('nem-ran', 'dau-an', 20),
  ('banh-bao', 'bot-mi', 70),
  ('banh-bao', 'nuoc-loc', 30),
  ('banh-bao', 'thit-heo-nac', 30),
  ('banh-bao', 'trung-ga', 15),
  ('banh-bao', 'duong-trang', 8),
  ('banh-bao', 'dau-an', 3),
  ('banh-chung', 'gao-nep', 120),
  ('banh-chung', 'dau-xanh', 30),
  ('banh-chung', 'thit-ba-chi', 40),
  ('banh-chung', 'nuoc-loc', 60),
  ('xoi-xeo', 'gao-nep', 100),
  ('xoi-xeo', 'dau-xanh', 25),
  ('xoi-xeo', 'nuoc-loc', 70),
  ('xoi-xeo', 'dau-an', 10),
  ('com-chien-duong-chau', 'com-trang', 250),
  ('com-chien-duong-chau', 'lap-xuong', 30),
  ('com-chien-duong-chau', 'trung-ga', 40),
  ('com-chien-duong-chau', 'tom-tuoi', 30),
  ('com-chien-duong-chau', 'ca-rot', 20),
  ('com-chien-duong-chau', 'dau-an', 12),
  ('thit-kho-tau', 'thit-ba-chi', 120),
  ('thit-kho-tau', 'trung-vit', 60),
  ('thit-kho-tau', 'nuoc-dua', 50),
  ('thit-kho-tau', 'nuoc-mam', 12),
  ('thit-kho-tau', 'duong-trang', 8),
  ('ga-kho-gung', 'thit-ga-ta', 150),
  ('ga-kho-gung', 'nuoc-mam', 12),
  ('ga-kho-gung', 'duong-trang', 6),
  ('ga-kho-gung', 'dau-an', 6),
  ('suon-xao-chua-ngot', 'suon-heo', 150),
  ('suon-xao-chua-ngot', 'ca-chua', 40),
  ('suon-xao-chua-ngot', 'duong-trang', 10),
  ('suon-xao-chua-ngot', 'dau-an', 10),
  ('suon-xao-chua-ngot', 'nuoc-mam', 8),
  ('suon-nuong', 'suon-heo', 150),
  ('suon-nuong', 'nuoc-mam', 10),
  ('suon-nuong', 'duong-trang', 8),
  ('suon-nuong', 'dau-an', 5),
  ('suon-nuong', 'toi', 5),
  ('bo-luc-lac', 'thit-bo-nac', 150),
  ('bo-luc-lac', 'hanh-tay', 50),
  ('bo-luc-lac', 'dau-an', 12),
  ('bo-luc-lac', 'nuoc-tuong', 8),
  ('bo-luc-lac', 'toi', 5),
  ('muc-xao-hanh-tay', 'muc', 150),
  ('muc-xao-hanh-tay', 'hanh-tay', 60),
  ('muc-xao-hanh-tay', 'dau-an', 10),
  ('muc-xao-hanh-tay', 'nuoc-mam', 6),
  ('ca-hoi-ap-chao', 'ca-hoi', 150),
  ('ca-hoi-ap-chao', 'dau-an', 5),
  ('ca-hoi-ap-chao', 'muoi-an', 1),
  ('ga-luoc', 'thit-ga-ta', 150),
  ('ga-luoc', 'muoi-an', 1),
  ('uc-ga-ap-chao', 'uc-ga', 150),
  ('uc-ga-ap-chao', 'dau-an', 5),
  ('uc-ga-ap-chao', 'muoi-an', 1),
  ('dau-hu-nhoi-thit', 'dau-hu', 150),
  ('dau-hu-nhoi-thit', 'thit-heo-nac', 50),
  ('dau-hu-nhoi-thit', 'ca-chua', 80),
  ('dau-hu-nhoi-thit', 'dau-an', 10),
  ('dau-hu-nhoi-thit', 'nuoc-mam', 6),
  ('vit-quay', 'thit-vit', 150),
  ('vit-quay', 'nuoc-tuong', 8),
  ('vit-quay', 'duong-trang', 5),
  ('ga-ran', 'thit-ga-ta', 120),
  ('ga-ran', 'bot-mi', 15),
  ('ga-ran', 'dau-an', 15),
  ('canh-bi-dao-thit', 'bi-dao', 150),
  ('canh-bi-dao-thit', 'thit-heo-nac', 40),
  ('canh-bi-dao-thit', 'nuoc-loc', 100),
  ('canh-bi-dao-thit', 'nuoc-mam', 5),
  ('canh-bi-do-thit', 'bi-do', 150),
  ('canh-bi-do-thit', 'thit-heo-nac', 40),
  ('canh-bi-do-thit', 'nuoc-loc', 100),
  ('canh-bi-do-thit', 'nuoc-mam', 5),
  ('dau-que-xao-toi', 'dau-que', 150),
  ('dau-que-xao-toi', 'toi', 5),
  ('dau-que-xao-toi', 'dau-an', 8),
  ('dau-que-xao-toi', 'nuoc-mam', 5),
  ('bap-cai-luoc', 'bap-cai', 200),
  ('bap-cai-luoc', 'nuoc-mam', 5),
  ('bong-cai-xao-toi', 'bong-cai-xanh', 150),
  ('bong-cai-xao-toi', 'toi', 5),
  ('bong-cai-xao-toi', 'dau-an', 8),
  ('bong-cai-xao-toi', 'nuoc-mam', 5),
  ('ca-tim-nuong-mo-hanh', 'ca-tim', 200),
  ('ca-tim-nuong-mo-hanh', 'dau-an', 10),
  ('ca-tim-nuong-mo-hanh', 'hanh-la', 10),
  ('ca-tim-nuong-mo-hanh', 'nuoc-mam', 8),
  ('goi-ga-bap-cai', 'thit-ga-ta', 80),
  ('goi-ga-bap-cai', 'bap-cai', 100),
  ('goi-ga-bap-cai', 'ca-rot', 30),
  ('goi-ga-bap-cai', 'hanh-tay', 20),
  ('goi-ga-bap-cai', 'dau-phong', 10),
  ('goi-ga-bap-cai', 'nuoc-mam', 10),
  ('goi-ga-bap-cai', 'duong-trang', 8),
  ('salad-uc-ga', 'uc-ga', 100),
  ('salad-uc-ga', 'xa-lach', 80),
  ('salad-uc-ga', 'ca-chua', 50),
  ('salad-uc-ga', 'dua-leo', 50),
  ('salad-uc-ga', 'dau-an', 10),
  ('banh-mi-pate', 'banh-mi', 100),
  ('banh-mi-pate', 'pate', 30),
  ('banh-mi-pate', 'cha-lua', 20),
  ('banh-mi-pate', 'dua-leo', 20),
  ('banh-mi-pate', 'mayonnaise', 10),
  ('hamburger-bo', 'banh-mi', 90),
  ('hamburger-bo', 'thit-bo-nac', 70),
  ('hamburger-bo', 'dau-an', 8),
  ('hamburger-bo', 'pho-mai', 20),
  ('hamburger-bo', 'xa-lach', 15),
  ('hamburger-bo', 'ca-chua', 20),
  ('hamburger-bo', 'tuong-ca', 10),
  ('hamburger-bo', 'mayonnaise', 10),
  ('pizza', 'bot-mi', 40),
  ('pizza', 'nuoc-loc', 30),
  ('pizza', 'pho-mai', 20),
  ('pizza', 'xuc-xich', 12),
  ('pizza', 'tuong-ca', 10),
  ('pizza', 'ca-chua', 10),
  ('pizza', 'dau-an', 3),
  ('yen-mach-sua-chuoi', 'yen-mach', 40),
  ('yen-mach-sua-chuoi', 'sua-tuoi-khong-duong', 200),
  ('yen-mach-sua-chuoi', 'chuoi-tieu', 50),
  ('bap-luoc', 'ngo-ngot', 150),
  ('khoai-mi-hap', 'khoai-mi', 150),
  ('banh-trang-tron', 'banh-trang', 50),
  ('banh-trang-tron', 'trung-ga', 20),
  ('banh-trang-tron', 'xoai-chin', 30),
  ('banh-trang-tron', 'dau-phong', 10),
  ('banh-trang-tron', 'dau-an', 10),
  ('banh-trang-tron', 'muc', 10),
  ('banh-trang-tron', 'duong-trang', 5),
  ('trung-vit-lon-luoc', 'trung-vit-lon', 60),
  ('trung-vit-lon-luoc', 'muoi-an', 1)
),
stale as (
  delete from public.dish_components dc
  using public.foods d, public.foods i
  where dc.dish_id = d.id
    and dc.ingredient_id = i.id
    and d.slug in (select dish_slug from component_seed)
    and not exists (
      select 1 from component_seed s
      where s.dish_slug = d.slug and s.ingredient_slug = i.slug
    )
)
insert into public.dish_components (dish_id, ingredient_id, grams)
select d.id, i.id, s.grams
from component_seed s
join public.foods d on d.slug = s.dish_slug
join public.foods i on i.slug = s.ingredient_slug
on conflict (dish_id, ingredient_id) do update set grams = excluded.grams;

-- 4. Tính lại chỉ số của món từ thành phần vừa nạp.
--    Bước này khiến CSDL trở thành nguồn chân lý: dù file trên có sai sót,
--    con số cuối cùng vẫn nhất quán với thành phần.
select public.recompute_dish_nutrients(id) from public.foods where kind = 'dish';

-- 5. Danh mục bài tập
--    MET là nguồn chân lý để tính kcal đốt của buổi tập; không được để model tự đoán.
insert into public.exercises (slug, name_vi, muscle_group, equipment, level, measure, met, contraindications, cue, source_ref)
values
  ('squat-bodyweight', 'Squat không tạ', 'legs', 'bodyweight', 'beginner', 'reps', 5, '{}'::public.injury_area[], 'Hạ hông như ngồi xuống ghế, đầu gối hướng theo mũi chân.', 'MET theo 2011 Compendium of Physical Activities'),
  ('squat-goblet', 'Goblet squat', 'legs', 'dumbbell', 'beginner', 'reps', 5, '{}'::public.injury_area[], 'Ôm tạ trước ngực, giữ thân trên thẳng.', 'MET theo 2011 Compendium of Physical Activities'),
  ('lunge', 'Chùng chân (lunge)', 'legs', 'bodyweight', 'beginner', 'reps', 5, array['knee']::public.injury_area[], 'Bước tới, hạ gối sau gần sàn rồi đẩy về.', 'MET theo 2011 Compendium of Physical Activities'),
  ('deadlift-romanian', 'Romanian deadlift', 'glutes', 'barbell', 'intermediate', 'reps', 6, array['lower_back']::public.injury_area[], 'Đẩy hông ra sau, giữ lưng thẳng, cảm nhận căng mặt sau đùi.', 'MET theo 2011 Compendium of Physical Activities'),
  ('hip-thrust', 'Hip thrust', 'glutes', 'barbell', 'intermediate', 'reps', 5, '{}'::public.injury_area[], 'Tựa lưng trên ghế, siết mông ở đỉnh rồi hạ chậm.', 'MET theo 2011 Compendium of Physical Activities'),
  ('calf-raise', 'Nhón gót', 'legs', 'bodyweight', 'beginner', 'reps', 3.5, '{}'::public.injury_area[], 'Lên hết cỡ rồi hạ chậm, không nảy.', 'MET theo 2011 Compendium of Physical Activities'),
  ('leg-press', 'Đạp đùi máy', 'legs', 'machine', 'beginner', 'reps', 5, '{}'::public.injury_area[], 'Không khoá khớp gối ở đỉnh.', 'MET theo 2011 Compendium of Physical Activities'),
  ('push-up', 'Hít đất', 'chest', 'bodyweight', 'beginner', 'reps', 4.3, array['wrist', 'shoulder']::public.injury_area[], 'Thân người thành một đường thẳng, khuỷu tay hơi khép.', 'MET theo 2011 Compendium of Physical Activities'),
  ('bench-press', 'Đẩy ngực ghế ngang', 'chest', 'barbell', 'intermediate', 'reps', 5, array['shoulder']::public.injury_area[], 'Siết vai về sau, hạ tạ tới ngang ngực.', 'MET theo 2011 Compendium of Physical Activities'),
  ('dumbbell-shoulder-press', 'Đẩy vai tạ đơn', 'shoulders', 'dumbbell', 'beginner', 'reps', 5, array['shoulder']::public.injury_area[], 'Đẩy thẳng lên, không ưỡn lưng.', 'MET theo 2011 Compendium of Physical Activities'),
  ('lateral-raise', 'Nâng vai ngang', 'shoulders', 'dumbbell', 'beginner', 'reps', 4, '{}'::public.injury_area[], 'Nâng tới ngang vai, khuỷu hơi cong.', 'MET theo 2011 Compendium of Physical Activities'),
  ('triceps-dip', 'Chống xà kép', 'arms', 'bodyweight', 'intermediate', 'reps', 5, array['shoulder', 'wrist']::public.injury_area[], 'Hạ tới khi khuỷu vuông góc rồi đẩy lên.', 'MET theo 2011 Compendium of Physical Activities'),
  ('pull-up', 'Hít xà', 'back', 'bodyweight', 'advanced', 'reps', 8, array['shoulder', 'wrist']::public.injury_area[], 'Kéo bằng lưng, không đung đưa người.', 'MET theo 2011 Compendium of Physical Activities'),
  ('lat-pulldown', 'Kéo xô máy', 'back', 'machine', 'beginner', 'reps', 5, '{}'::public.injury_area[], 'Kéo thanh về ngực trên, siết xô ở cuối.', 'MET theo 2011 Compendium of Physical Activities'),
  ('seated-row', 'Kéo cáp ngồi', 'back', 'machine', 'beginner', 'reps', 5, '{}'::public.injury_area[], 'Giữ lưng thẳng, kéo khuỷu ra sau.', 'MET theo 2011 Compendium of Physical Activities'),
  ('band-row', 'Kéo dây kháng lực', 'back', 'band', 'beginner', 'reps', 4, '{}'::public.injury_area[], 'Siết bả vai lại với nhau ở cuối động tác.', 'MET theo 2011 Compendium of Physical Activities'),
  ('biceps-curl', 'Cuốn tay trước', 'arms', 'dumbbell', 'beginner', 'reps', 3.5, '{}'::public.injury_area[], 'Giữ khuỷu cố định, không vung người.', 'MET theo 2011 Compendium of Physical Activities'),
  ('plank', 'Plank', 'core', 'bodyweight', 'beginner', 'time', 3.5, '{}'::public.injury_area[], 'Siết bụng và mông, giữ hông không võng.', 'MET theo 2011 Compendium of Physical Activities'),
  ('dead-bug', 'Dead bug', 'core', 'bodyweight', 'beginner', 'reps', 3, '{}'::public.injury_area[], 'Giữ lưng dưới áp sàn suốt động tác.', 'MET theo 2011 Compendium of Physical Activities'),
  ('russian-twist', 'Xoay người kiểu Nga', 'core', 'bodyweight', 'intermediate', 'reps', 4, array['lower_back']::public.injury_area[], 'Xoay từ thân trên, không kéo bằng tay.', 'MET theo 2011 Compendium of Physical Activities'),
  ('hanging-leg-raise', 'Treo xà nâng chân', 'core', 'bodyweight', 'advanced', 'reps', 5, array['shoulder', 'lower_back']::public.injury_area[], 'Nâng chân có kiểm soát, không đung đưa.', 'MET theo 2011 Compendium of Physical Activities'),
  ('walking-brisk', 'Đi bộ nhanh', 'cardio', 'bodyweight', 'beginner', 'time', 4.3, '{}'::public.injury_area[], 'Đi nhanh tới mức nói được nhưng không hát được.', 'MET theo 2011 Compendium of Physical Activities'),
  ('running', 'Chạy bộ', 'cardio', 'bodyweight', 'intermediate', 'time', 9.8, array['knee', 'ankle']::public.injury_area[], 'Tiếp đất bằng giữa bàn chân, nhịp thở đều.', 'MET theo 2011 Compendium of Physical Activities'),
  ('cycling', 'Đạp xe', 'cardio', 'cardio_machine', 'beginner', 'time', 7.5, '{}'::public.injury_area[], 'Giữ nhịp đều, điều chỉnh lực cản vừa sức.', 'MET theo 2011 Compendium of Physical Activities'),
  ('rowing', 'Chèo thuyền máy', 'full_body', 'cardio_machine', 'intermediate', 'time', 7, array['lower_back']::public.injury_area[], 'Đẩy bằng chân trước, rồi mới kéo tay.', 'MET theo 2011 Compendium of Physical Activities'),
  ('jump-rope', 'Nhảy dây', 'cardio', 'bodyweight', 'intermediate', 'time', 10, array['knee', 'ankle']::public.injury_area[], 'Nhảy thấp, tiếp đất nhẹ bằng mũi chân.', 'MET theo 2011 Compendium of Physical Activities'),
  ('burpee', 'Burpee', 'full_body', 'bodyweight', 'advanced', 'time', 8, array['knee', 'lower_back', 'wrist']::public.injury_area[], 'Giữ nhịp đều, hạ xuống bằng tay chắc.', 'MET theo 2011 Compendium of Physical Activities'),
  ('mountain-climber', 'Leo núi tại chỗ', 'full_body', 'bodyweight', 'intermediate', 'time', 8, array['wrist']::public.injury_area[], 'Hông giữ thấp, đổi chân nhanh.', 'MET theo 2011 Compendium of Physical Activities'),
  ('kettlebell-swing', 'Vung tạ ấm', 'full_body', 'dumbbell', 'intermediate', 'reps', 9.8, array['lower_back']::public.injury_area[], 'Lực phát ra từ hông, tay chỉ giữ tạ.', 'MET theo 2011 Compendium of Physical Activities'),
  ('arm-circle', 'Xoay vai khởi động', 'mobility', 'bodyweight', 'beginner', 'time', 2.3, '{}'::public.injury_area[], 'Xoay chậm, tăng dần biên độ.', 'MET theo 2011 Compendium of Physical Activities'),
  ('cat-cow', 'Mèo–bò giãn cột sống', 'mobility', 'bodyweight', 'beginner', 'time', 2.3, '{}'::public.injury_area[], 'Phối hợp hơi thở với chuyển động.', 'MET theo 2011 Compendium of Physical Activities'),
  ('hip-opener', 'Giãn hông', 'mobility', 'bodyweight', 'beginner', 'time', 2.3, '{}'::public.injury_area[], 'Giữ 30 giây mỗi bên, không nảy.', 'MET theo 2011 Compendium of Physical Activities'),
  ('hamstring-stretch', 'Giãn mặt sau đùi', 'mobility', 'bodyweight', 'beginner', 'time', 2.3, '{}'::public.injury_area[], 'Giữ thẳng lưng, gập từ hông.', 'MET theo 2011 Compendium of Physical Activities')
on conflict (slug) do update set
    name_vi = excluded.name_vi,
    muscle_group = excluded.muscle_group,
    equipment = excluded.equipment,
    level = excluded.level,
    measure = excluded.measure,
    met = excluded.met,
    contraindications = excluded.contraindications,
    cue = excluded.cue,
    source_ref = excluded.source_ref
;
